BEGIN;

INSERT INTO classes (name, code, section, semester) VALUES ('Designing Interfaces for Live Performance', 'IMNY-UT 243', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Physical Computing', 'IMNY-UT 245', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Fabrication Re-Plasticing', 'IMNY-UT 251', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Digital Fabrication', 'IMNY-UT 252', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interaction as Art Medium', 'IMNY-UT 253', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Media Art (...)', 'IMNY-UT 260', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Design Fundamentals', 'IMNY-UT 261', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('User Experience Design', 'IMNY-UT 262', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Design Information Design', 'IMNY-UT 270', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Useless Machines', 'IMNY-UT 272', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Media Art (...)', 'IMNY-UT 281', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Immersive Experiences', 'IMNY-UT 282', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Animation: Methods of Motion', 'IMNY-UT 288', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Non-Linear Storytelling Structures | Storytelling for Project Development', 'IMNY-UT 291', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Alter Egos', 'IMNY-UT 297', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Capstone', 'IMNY-UT 400', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Augmenting the Gallery', 'IMNY-UT 9001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'IMNY-UT 901', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Media Art Performing Emerging Forms', 'IMNY-UT 9260', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Media Art Transmedia Storytelling', 'IMNY-UT 9281', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The American Musical', 'GMTW-UT 1002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Art of Make Up for Film & Television', 'OART-UT 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Producing Essentials', 'OART-UT 1006', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art and Social Change', 'OART-UT 1018', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art on the Edge', 'OART-UT 1019', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Improvising Sound and Music', 'OART-UT 1021', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Villain', 'OART-UT 1024', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Playwriting Practicum', 'OART-UT 1040', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing Your Life', 'OART-UT 1047', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Musical Theatre Writing Workshop', 'OART-UT 1050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Abrupt Climate Change', 'OART-UT 1058', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art and Technology | Experiments in Art and Technology', 'OART-UT 1059', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Reality and Creation', 'OART-UT 106', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Fundraising', 'OART-UT 1093', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Music Applications', 'OART-UT 1095', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Analog Photography', 'OART-UT 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Film: A Transformative Process, a Vision Beyond Technology', 'OART-UT 140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Devised Theater: History and Practice', 'OART-UT 144', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Embodied Performance: Collaborative Creations', 'OART-UT 145', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Designing Motion', 'OART-UT 149', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Documentary Film', 'OART-UT 1701', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experiments in Collective Joy', 'OART-UT 18', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Movement as Play', 'OART-UT 1901', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theatrical Genres', 'OART-UT 1903', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dream Play', 'OART-UT 1904', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Acting I: Introduction to the Actor''s Craft', 'OART-UT 1906', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Acting on Camera', 'OART-UT 1908', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Reimagining Shakespeare: The Bard Out Loud for the 21st Century', 'OART-UT 1909', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Collaborative Arts Theatre Experience', 'OART-UT 1917', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Live in New York City', 'OART-UT 1921', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Casting and Auditioning', 'OART-UT 1926', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Acting and Performance on Camera | Advanced Acting for the Camera', 'OART-UT 1931', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Electronics for Artists', 'OART-UT 22', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Animated Alchemy', 'OART-UT 23', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Zine Scenes', 'OART-UT 24', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performing Voice and Talking Machines', 'OART-UT 25', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('IRL/URL_Performing Hybrid Systems', 'OART-UT 28', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Universe in a Blender', 'OART-UT 29', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research: Manifestos and Arts Practice', 'OART-UT 298', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Small Lights at the End of the World', 'OART-UT 30', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hyper Object', 'OART-UT 31', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Artwear', 'OART-UT 33', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Movement Machines: Kinetic Art and Performance', 'OART-UT 34', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Screenwriting', 'OART-UT 35', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Screenwriting', 'OART-UT 36', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Touch Is a Point of Contact', 'OART-UT 43', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Wood: Structures and Stages', 'OART-UT 44', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Filmmaking I: The Art of Visual Storytelling', 'OART-UT 560', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Filmmaking II: Narrative Film', 'OART-UT 561', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media Moguls in the 20th Century', 'OART-UT 562', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Art of Adaptation Transforming Source Material into Film and TV', 'OART-UT 563', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cell Phone Cinema', 'OART-UT 566', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Live Video Performance Art', 'OART-UT 567', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Understanding Story', 'OART-UT 568', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('New Video Dimensions', 'OART-UT 569', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Audio Storytelling: Creative Nonfiction', 'OART-UT 572', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Phantom Projections', 'OART-UT 574', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Documentary Filmmaking II: Documentary Discovery - Directing & Producing', 'OART-UT 581', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Queer Cinema', 'OART-UT 582', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Why Dance Matters: Politics, Race, Class', 'OART-UT 703', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Bodies in Cultural Landscapes', 'OART-UT 706', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Dancing Body in Practice and Theory', 'OART-UT 707', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performing Anatomy: Body Technology', 'OART-UT 708', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Steps Rhythm Movement: African Dance', 'OART-UT 800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Dance: Mind-Body Knowledge and Expression', 'OART-UT 804', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Choreography', 'OART-UT 805', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ballet', 'OART-UT 806', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Steps Rhythm Movement: Hip Hop Dance', 'OART-UT 808', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Site­ Specific to Immersive Dance Theater: Choreographing/Unconventional formats', 'OART-UT 810', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ballet II', 'OART-UT 811', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Dance II: Mind-Body Integration | The Making of a Dance: From Practice to Production', 'OART-UT 812', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hyperreal Spectacle in Interactive Performance', 'OART-UT 816', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Choreocinema and the Expanding Eye', 'OART-UT 817', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Clown and Audience', 'OART-UT 818', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Digital Tools', 'OART-UT 823', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Politics of Portraiture', 'OART-UT 826', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Poetics of Witnessing', 'OART-UT 829', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance of the City', 'PERF-UT 103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance Composition', 'PERF-UT 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theories of Movement', 'PERF-UT 303', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Performance Studies (...)', 'PERF-UT 305', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Race and Performance', 'PERF-UT 306', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance Studies Supervised Internship Course', 'PERF-UT 307', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Capstone Project', 'PERF-UT 401', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance of the City:', 'PERF-UT 9103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photography & Imaging Digital', 'PHTI-UT 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photoshop:', 'PHTI-UT 1007', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Lighting:', 'PHTI-UT 1013', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Large Format', 'PHTI-UT 1014', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Emerging Media Studio: Digital Bodies', 'PHTI-UT 1018', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Directed Projects: I Junior Seminar', 'PHTI-UT 1030', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business of Art', 'PHTI-UT 1100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced History Seminar (...)', 'PHTI-UT 1120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Editorial Content for New Media', 'PHTI-UT 1203', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Documentary', 'PHTI-UT 1216', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Digital Printing', 'PHTI-UT 1236', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'PHTI-UT 1300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Anatomy of the Book', 'PHTI-UT 1400', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'PHTI-UT 1500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study Abroad', 'PHTI-UT 1501', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Visual Culture Colloquium', 'PHTI-UT 1650', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photography & Imaging Analog', 'PHTI-UT 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photography & Imaging 3 (...)', 'PHTI-UT 3', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Producing The Record: Side B', 'REMU-UT 1004', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Content Development for Performers, Producers, & Songwriters', 'REMU-UT 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Virtual Producer: Live Performance with Laptops & Software', 'REMU-UT 1017', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Audio Workstations: Logic', 'REMU-UT 1021', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Synthesis and Sound Design in Popular Music I: 1960 - 1983', 'REMU-UT 1024', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Ableton Live for Music Production & Sound Design', 'REMU-UT 1025', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Professional Development: Internship', 'REMU-UT 1037', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Engineering The Record II', 'REMU-UT 1041', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mix Intensive', 'REMU-UT 1052', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Classic Drum Breaks: Sampling and Recording | The Art of Recording Classic Drums', 'REMU-UT 1070', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Words Matter: Lyrics In History & Practice', 'REMU-UT 1084', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Max Martin: The Musical Architecture of the Number Ones', 'REMU-UT 1085', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('New Perspectives in Latin Music: The North', 'REMU-UT 1087', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Adv Musicianship:Small Group Instrumental/Music Theory Application Instruction (...)', 'REMU-UT 1091', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Songwriting Workshop', 'REMU-UT 1093', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Critical Listening for the Recording Studio', 'REMU-UT 1102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Recorded Music: Miles Davis', 'REMU-UT 1111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Women as Entrepreneurs in Popular Music', 'REMU-UT 1170', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music and Spirituality Across the World', 'REMU-UT 1176', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Recorded Music: The Reggaeton Revolution', 'REMU-UT 1179', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Recorded Music: Quincy Jones', 'REMU-UT 1183', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Recorded Music: Beyonce', 'REMU-UT 1184', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Recorded Music: Nipsey Hussle: the Path of the Activist Artist', 'REMU-UT 1185', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mastering the Emergent Media Landscape:Professionalizing Your Writing & Storytelling Skills', 'REMU-UT 1196', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing & Reporting Music', 'REMU-UT 1200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Music Entrepreneurs in Historical Context', 'REMU-UT 1201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('How the Contemporary Music Business Works', 'REMU-UT 1202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Artists & Audiences in Historical Context', 'REMU-UT 1203', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('How Music Marketing Works: Building Your Audience, Clients, and Customer Base', 'REMU-UT 1205', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Project Management', 'REMU-UT 1207', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Professional Development: Global Engagement', 'REMU-UT 1219', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Contracts & Dealmaking', 'REMU-UT 1223', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Future of the Music Streaming Economy', 'REMU-UT 1231', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('3D Printing & the Music Industry', 'REMU-UT 1234', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Basics of Music Licensing', 'REMU-UT 1240', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Basics of Artist Management', 'REMU-UT 1262', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Developing A Business Plan For Your Music Venture', 'REMU-UT 1272', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Studio Performance Workshop: Songwriting, Arranging, Production & Performance', 'REMU-UT 1301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creating a Compelling Live Performance: From Concept to Concert', 'REMU-UT 1310', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Body & the Stage', 'REMU-UT 1311', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Business of Touring & Live Events', 'REMU-UT 1323', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance Essentials: Vocal Techniques', 'REMU-UT 1326', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance Essentials: Stagecraft', 'REMU-UT 1327', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vocal Coaching: Private Instruction', 'REMU-UT 1331', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Professional Development: Preparing Your Post-Graduate Plan', 'REMU-UT 1401', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Professional Development: Pursuing Your Post-Graduate Plan', 'REMU-UT 1402', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'REMU-UT 1500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Women as Entrepreneurs in Popular Music', 'REMU-UT 9170', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Supervision for Filmmakers and Creative Music Entrepreneurs', 'REMU-UT 9242', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experiments in Film & Media', 'FMTV-UT 1002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Production Sound', 'FMTV-UT 1004', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Studio Recording', 'FMTV-UT 1005', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Art of Sound', 'FMTV-UT 1007', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Production Safety and Set Protocol', 'FMTV-UT 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sound Mix Workshop', 'FMTV-UT 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Production Sound', 'FMTV-UT 1012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Editing I', 'FMTV-UT 1016', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Television Writing', 'FMTV-UT 1017', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Editing II', 'FMTV-UT 1018', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Preparing The Screenplay', 'FMTV-UT 1019', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing the Short Screenplay', 'FMTV-UT 1020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Producing the Short Screenplay', 'FMTV-UT 1023', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Actor''s Craft I', 'FMTV-UT 1024', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Producing for TV', 'FMTV-UT 1028', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Traditions in Narrative', 'FMTV-UT 1031', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Storyboarding', 'FMTV-UT 1033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Documentary Traditions II', 'FMTV-UT 1034', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media Internship I', 'FMTV-UT 1037', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media Internship II', 'FMTV-UT 1038', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media Internship', 'FMTV-UT 1039', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Narrative Production', 'FMTV-UT 1040', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Motion Design and Titles', 'FMTV-UT 1042', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Experimental Workshop', 'FMTV-UT 1046', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Production Design for Film & Television', 'FMTV-UT 1048', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Production Workshop I', 'FMTV-UT 1053', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Production Workshop II', 'FMTV-UT 1054', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Colloquium: Exit Strategies', 'FMTV-UT 1057', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sound Design I', 'FMTV-UT 1059', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sound Design II', 'FMTV-UT 1060', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Documentary Workshop: Sports Documentary', 'FMTV-UT 1061', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Science of Cinematography', 'FMTV-UT 1063', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Camera I: Principles and Practices of Cinematography', 'FMTV-UT 1065', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Camera II: Applied Cinematography', 'FMTV-UT 1066', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Camera III: Cinematography for Advanced Productions', 'FMTV-UT 1067', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Directing The Actor', 'FMTV-UT 1069', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Directing The Camera', 'FMTV-UT 1070', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Documentary Production Workshop', 'FMTV-UT 1080', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Script Analysis', 'FMTV-UT 1084', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('TV Nation: Inside and Out of The Box', 'FMTV-UT 1086', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Strategies for Independent Producing', 'FMTV-UT 1092', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Producing for Film', 'FMTV-UT 1095', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Independent Study', 'FMTV-UT 1097', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Independent Study', 'FMTV-UT 1098', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Developing the Screenplay', 'FMTV-UT 1100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing for Television: The Half Hour', 'FMTV-UT 1102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Editing III', 'FMTV-UT 1105', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to 3D', 'FMTV-UT 1110', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Life Drawing: The Figure', 'FMTV-UT 1112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics in 3-D Animation (...)', 'FMTV-UT 1113', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Animation: From Pitching To Pipeline To Production', 'FMTV-UT 1116', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research & Writing for Documentary', 'FMTV-UT 1118', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internet Design', 'FMTV-UT 1123', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing for Children''s Television', 'FMTV-UT 1126', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Writing for Television | Writing for Advanced TV: Production Workshop', 'FMTV-UT 1131', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing For Television: The Hour', 'FMTV-UT 1132', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Post Production Finishing for Editors', 'FMTV-UT 1141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Visual Effects and Compositing', 'FMTV-UT 1143', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experimental Animation', 'FMTV-UT 1146', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Experimental Workshop Film', 'FMTV-UT 1147', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Adaptation Screenwriting Workshop', 'FMTV-UT 1152', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Visual Effects for Animated and Live Action Films', 'FMTV-UT 1153', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hollywood Auteurs', 'FMTV-UT 1154', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italian Cinema', 'FMTV-UT 1155', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing for Late Night Television', 'FMTV-UT 1158', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Art of Makeup for Film & Television', 'FMTV-UT 1171', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Alternative Screenwriting', 'FMTV-UT 1184', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Legal Aspects of The Entertainment Industry', 'FMTV-UT 1195', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Producing for Animation', 'FMTV-UT 1196', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Film Analysis', 'FMTV-UT 1204', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ecocinema', 'FMTV-UT 1205', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Black Image in Cinema', 'FMTV-UT 1216', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Queerness in American Cinema', 'FMTV-UT 1217', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing the Micro Budget Feature', 'FMTV-UT 1219', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Feature Writing II', 'FMTV-UT 1221', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Children''s Television Production Workshop', 'FMTV-UT 1222', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Post Production Finishing for Directors and Cinematographers', 'FMTV-UT 1241', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Narrative Workshop', 'FMTV-UT 1245', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Short Commercial Forms', 'FMTV-UT 1246', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Production Design for Film & Television', 'FMTV-UT 1248', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Directors Process', 'FMTV-UT 125', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Sound Techniques for Transfer Students', 'FMTV-UT 1274', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Production Management: Boards and Budgets', 'FMTV-UT 1296', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Lifedrawing: Anatomy', 'FMTV-UT 1312', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Action Analysis II', 'FMTV-UT 1327', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Action Analysis I', 'FMTV-UT 1328', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Animation Production II', 'FMTV-UT 1343', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance Strategies for Transfers', 'FMTV-UT 146', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Storytelling Strategies', 'FMTV-UT 20', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dual Degree Colloquium', 'FMTV-UT 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('TV Programming & Concepts', 'FMTV-UT 21', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Stop Motion Animation', 'FMTV-UT 214', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experimental Screenwriting', 'FMTV-UT 246', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Generative Filmmaking in the Age of Hypercinema', 'FMTV-UT 260', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Cinema: 1960 to Present', 'FMTV-UT 322', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Cinema: 1960 to Present', 'FMTV-UT 324', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Frame & Sequence', 'FMTV-UT 39', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Language of Film', 'FMTV-UT 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Animation Techniques', 'FMTV-UT 41', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sight & Sound: Filmmaking', 'FMTV-UT 43', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Freshmen Colloquium: Performance Strategies', 'FMTV-UT 46', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First Person Narrative', 'FMTV-UT 47', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sound Image', 'FMTV-UT 48', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Freshmen Colloquium: Art & Practice', 'FMTV-UT 49', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sight & Sound: Studio', 'FMTV-UT 51', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Pre-Production Colloquium', 'FMTV-UT 59', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sight & Sound: Documentary', 'FMTV-UT 80', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Arts in London:', 'ISPEC-UT 1301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Lives in Brief', 'WRTNG-UG 1026', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing About Popular Music', 'WRTNG-UG 1039', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Age of Listening', 'WRTNG-UG 1048', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing for Children: Magic, Memoir, and Mystery', 'WRTNG-UG 1355', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing Queer YA Fiction', 'WRTNG-UG 1365', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing Cultural Criticism: American Comedy', 'WRTNG-UG 1507', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Story Sense: Narrative Across Mediums', 'WRTNG-UG 1523', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing the Portrait: Depicting Artists in Fiction', 'WRTNG-UG 1529', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Short Story: a Workshop in Revising', 'WRTNG-UG 1536', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Crafting Short Fiction from the Sentence Up', 'WRTNG-UG 1537', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fiction Writing', 'WRTNG-UG 1550', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Art and Craft of Poetry', 'WRTNG-UG 1560', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fault Lines: Writing Memoir', 'WRTNG-UG 1566', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Criticism + Value', 'WRTNG-UG 1567', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Reporting Places', 'WRTNG-UG 1575', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Writing: Argentina, travel Writing at the End of the World', 'WRTNG-UG 9150', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Keeping It Real: Realism in Writing and Acting on Stage', 'ARTS-UG 1007', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Oral History, Cultural Identity and The Arts', 'ARTS-UG 1045', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Contemporary Broadway Musical: Rent to Hamilton (and Beyond)', 'ARTS-UG 1058', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Arts Therapies: Supporting and Transforming Communities through the Arts', 'ARTS-UG 1115', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Scores and Structures for Dance and Performance: Making the Process Visible', 'ARTS-UG 1210', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('World Dance and Global Perspectives', 'ARTS-UG 1212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Delicious Movement: Time Is Not Even, Space Is Not Empty', 'ARTS-UG 1275', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creating Music, Composing Worlds', 'ARTS-UG 1320', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creating a Full-Length Text/Music Performance and Recording', 'ARTS-UG 1341', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Improvisation: Concepts and Practice', 'ARTS-UG 1345', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Averting Evil and the Affective Image', 'ARTS-UG 1412', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Discovering Manhattan: Drawing and Painting in the Spirit of the Modern Art Pioneers', 'ARTS-UG 1425', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Mexican Muralists and Their Indigenous Influences, and the American Artists They Influence', 'ARTS-UG 1432', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fashion as Art: Contemporary Collaborations', 'ARTS-UG 1437', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Copy', 'ARTS-UG 1463', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photograph New York, Create Your Vision', 'ARTS-UG 1480', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing for The Screen II', 'ARTS-UG 1573', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Craft and Art of Directing for the Screen', 'ARTS-UG 1599', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Architecture and Urban Design Lab', 'ARTS-UG 1614', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Green Design and Planning', 'ARTS-UG 1623', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Design with Climate Change', 'ARTS-UG 1636', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Culture of Nature', 'ARTS-UG 1637', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Garden of Forking Paths: Exploring the Interactive Story', 'ARTS-UG 1642', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Future Reality: Trends and Impact of New Media', 'ARTS-UG 1643', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance Art: Progress as a Radical Outsider', 'ARTS-UG 1662', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Events, Objects, and Actions: Making an Arts Festival', 'ARTS-UG 1800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing An Original Television Pilot', 'ARTS-UG 1803', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fall Arts Intensive: Dramatic Writing | Spring Arts Intensive: Writing for Stage and Screen', 'ARTS-UG 1806', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art and Activism in Madrid''s Spanish-speaking Diaspora Communities', 'ARTS-UG 9300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First Year Research Seminar: Advising', 'FIRST-UG 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Transfer Student Research Seminar: The Politics of Work', 'FIRST-UG 1811', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Sem: Language & The Political', 'FIRST-UG 709', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: The Cold War: What Was It and Why Does It Matter?', 'FIRST-UG 740', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Sem: Examining the Mundane: Art and Literature of the Everyday', 'FIRST-UG 760', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Shadow Cities: Literary Alterity and Urban Underworlds', 'FIRST-UG 778', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Sounds Beneath Your Feet: Downtown Music and Downtown Memory', 'FIRST-UG 819', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Black Experiences in Literature, Movies, and Television', 'FIRST-UG 828', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First Year Research Seminar: The Politics of Abstraction', 'FIRST-UG 829', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Feminist Cultures of the US, 1960s-Present', 'FIRST-UG 831', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: The Suburban Imaginary and the American Dream', 'FIRST-UG 833', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Supreme Court in American Life', 'FIRST-UG 836', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Space, Place, and the Body: From Gentrification to Climate Justice', 'FIRST-UG 837', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Philosophical Approaches to Identity', 'FIRST-UG 840', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: The Art of Doing Nothing', 'FIRST-UG 841', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Africa, China, Globalization', 'FIRST-UG 845', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Reimagining the Museum for the 21st-Century', 'FIRST-UG 849', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Sem: Special Collections: Politics, Pleasures and Precarities of Black Archiving', 'FIRST-UG 858', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Watching the Detectives: Detective Fiction and The Problems of Knowing', 'FIRST-UG 860', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Coins, Crosses, and Icons: Histories through/of Objects', 'FIRST-UG 861', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Truth and Method in Western Thought', 'FIRST-UG 862', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Asian/American Labor: Past, Present, and Future', 'FIRST-UG 863', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First-Year Research Seminar: Journalistic Investigations', 'FIRST-UG 864', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Private Lesson', 'INDIV-UG 1701', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'INDIV-UG 1801', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'INDIV-UG 1901', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Project', 'INDIV-UG 1905', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tutorial: tba', 'INDIV-UG 1925', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('ACCRA: Experiential Learning Seminar', 'INDIV-UG 9050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('BERLIN: Experiential Learning Seminar', 'INDIV-UG 9100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('BUENOS AIRES: Experiential Learning Seminar', 'INDIV-UG 9150', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('BUENOS AIRES: Great World Texts', 'INDIV-UG 9152', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Florence: Experiential Learning Seminar', 'INDIV-UG 9200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('LONDON: Experiential Learning Seminar', 'INDIV-UG 9250', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('MADRID: Experiential Learning Seminar', 'INDIV-UG 9300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('PARIS: Experiential Learning Seminar', 'INDIV-UG 9350', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('PRAGUE: Experiential Learning Seminar', 'INDIV-UG 9400', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('TEL AVIV: Experiential Learning Seminar', 'INDIV-UG 9550', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('WASHINGTON, DC: Experiential Learning Seminar', 'INDIV-UG 9600', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experiential Learning Seminar', 'INDIV-UG 9700', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fate + Free Will in The Epic Tradition', 'IDSEM-UG 1116', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Free Speech and Democracy', 'IDSEM-UG 1144', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ethics for Dissenters', 'IDSEM-UG 1313', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Metaphor and Meaning', 'IDSEM-UG 1341', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Photographic Imaginary', 'IDSEM-UG 1387', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sports, Race and Politics', 'IDSEM-UG 1493', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Globalization: Promises and Discontents', 'IDSEM-UG 1518', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Arabian Nights', 'IDSEM-UG 1567', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Ethnographic Imagination', 'IDSEM-UG 1577', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media and Fashion', 'IDSEM-UG 1618', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Think Big: Global Issues and Ecological Solutions', 'IDSEM-UG 1628', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Political Economy of Development', 'IDSEM-UG 1636', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Health and Human Rights in The World Community', 'IDSEM-UG 1641', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Celebrity Culture', 'IDSEM-UG 1642', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('From Memory to Myth: The Mighty Charlemagne', 'IDSEM-UG 1651', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Concept of Race in Society and History', 'IDSEM-UG 1660', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Legal Fictions: Novel, Law, and Society', 'IDSEM-UG 1669', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Politics of Food', 'IDSEM-UG 1674', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Competing Images of the Sage: Confucius and Lao Tzu', 'IDSEM-UG 1695', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Cultural Poltics of Bad Taste', 'IDSEM-UG 1738', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('James Joyce and Interdisciplinary Modernism', 'IDSEM-UG 1743', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ruins, Fragments, and Archives', 'IDSEM-UG 1748', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Government and the Economy: What Every Citizen Should Know', 'IDSEM-UG 1768', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Minds and Bodies: A History of Neuroscience', 'IDSEM-UG 1801', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dystopian Fictions', 'IDSEM-UG 1807', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('In With The Old, Out With The New: Debates on "Tradition" in Western Music', 'IDSEM-UG 1823', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Enlightenment Subjects and Subjections', 'IDSEM-UG 1831', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Poetics and Politics of Mourning', 'IDSEM-UG 1835', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Psychoanalysis Beyond Freud', 'IDSEM-UG 1843', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Times of Trauma', 'IDSEM-UG 1865', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Poetry and the Politics of Decolonization', 'IDSEM-UG 1866', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Impressionism: Myths and Modernism', 'IDSEM-UG 1872', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Library and Laboratory: Trans-cultural Histories of Early Modern Science', 'IDSEM-UG 1876', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media, Democracy and the New Political', 'IDSEM-UG 1916', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food and Nature in Cities', 'IDSEM-UG 1925', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Philosophy Through Film', 'IDSEM-UG 1943', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Text and Performance: Approaches to Criticism and Creativity', 'IDSEM-UG 1948', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Thinking Diasporically: Postcolonialism and Migration', 'IDSEM-UG 1951', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Western History of Madness from the Bible to DSM-5', 'IDSEM-UG 1961', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Society and State in the Ottoman Empire', 'IDSEM-UG 1976', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Of Violence and the U.S. Empire: Militarization, Colonialism and Unruliness', 'IDSEM-UG 1977', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Collective Memory of Atrocity and Injustice', 'IDSEM-UG 1980', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Television: Problems in Contemporary Criticism', 'IDSEM-UG 1981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Psychoanalysis, Race and Racism', 'IDSEM-UG 1985', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Life Among the Machines', 'IDSEM-UG 2018', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('(De)Tangling the Business of Black Women''s Hair', 'IDSEM-UG 2024', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photographing Peace', 'IDSEM-UG 2045', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Border Fictions/Migration Narratives', 'IDSEM-UG 2052', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Politics of Science and Technology | Science, Technology and Environment', 'IDSEM-UG 2066', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vomiting Lobsters, Cat Pianos, and Radical Interdisciplinarity', 'IDSEM-UG 2086', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Practicum in Fashion Business', 'PRACT-UG 1301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Policy, Community, and Self', 'PRACT-UG 1475', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Exploring Entrepreneurship: From Dreaming to Doing', 'PRACT-UG 1803', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Fashion Industry: Italy', 'PRACT-UG 9200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Fashion Industry: Britain', 'PRACT-UG 9250', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('DAUS Seminar', 'AENR1-UC 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing Skills Seminar', 'AENR1-UC 9225', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Success Seminar', 'AENR1-UC 9805', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultural Anthropology', 'ANTH1-UC 5003', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('World Cultures: Asia', 'ANTH1-UC 5013', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('World Cultures: Latin America & The Caribbean', 'ANTH1-UC 5014', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Anthropology of Religion', 'ANTH1-UC 5047', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Applied Data Analytics II', 'ADAV1-UC 1001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Designing Data: Infographics', 'ADAV1-UC 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Visual Analytics', 'ADAV1-UC 1015', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Art II: Renaissance to Modern', 'ARTH1-UC 5431', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Visual Expressions in Society', 'ARTH1-UC 5443', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Arts: Jazz', 'ARTS1-UC 5411', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Arts: Photography: The World Through the Lens', 'ARTS1-UC 5414', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Arts: Collage & Mixed Media', 'ARTS1-UC 5432', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Arts: Fundamentals of Painting & Design', 'ARTS1-UC 5435', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Accounting Principles: Navigating the World of Financial Reporting | Principles of Accounting', 'BUSN1-UC 142', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Accounting', 'BUSN1-UC 171', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Finance', 'BUSN1-UC 172', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sustainable Management Principles', 'BUSN1-UC 376', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business Organization & Management', 'BUSN1-UC 504', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business Law', 'BUSN1-UC 544', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Marketing', 'BUSN1-UC 943', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Foundations of The Creative Process', 'CWRG1-UC 5240', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Prose Studio', 'CWRG1-UC 5241', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Focus on Technique:', 'CWRG1-UC 5244', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing for The Screen', 'CWRG1-UC 5275', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sp Tpcs in Creative Writing | Sp Tpcs in Creatve Wrtg', 'CWRG1-UC 5290', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Motion Design II: Effects and Compositing', 'DGCM1-UC 2236', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media Design II: Techniques and Convergence', 'DGCM1-UC 2238', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Information Design', 'DGCM1-UC 2270', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interactive Design II: Dynamic Interfaces', 'DGCM1-UC 2272', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Content Strategy CX for Digital Media', 'DGCM1-UC 312', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Audio Recording', 'FILV1-UC 2004', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Filmmaking II', 'FILV1-UC 2202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Editing I', 'FILV1-UC 2203', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Macroeconomics', 'ECON1-UC 301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Microeconomics', 'ECON1-UC 302', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermed Macroeconomics', 'ECON1-UC 342', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Urban Economics', 'ECON1-UC 363', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Economic Thought', 'ECON1-UC 6608', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing Workshop I | Writing for Exploration', 'EXWR1-UC 7502', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mastering Creative & Professional Writing Skills | Writing Workshop II', 'EXWR1-UC 7503', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Community Health', 'HEAL1-UC 2601', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Multicultural Issues in Healthcare', 'HEAL1-UC 2608', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Legal Aspects of Healthcare', 'HEAL1-UC 2670', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Quality & Patient Safety in Healthcare', 'HEAL1-UC 2682', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Behavioral Health: Mental Health Issues of Children and Adults', 'HEAL1-UC 2849', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Renaissance to Revolutn', 'HIST1-UC 5804', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The American Experience', 'HIST1-UC 5820', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary World', 'HIST1-UC 5822', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sp Topics in History The Black Death', 'HIST1-UC 5890', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tourism Impacts and Issues', 'TCHT1-UC 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Entrepreneurship', 'TCHT1-UC 1050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Hospitality', 'TCHT1-UC 1070', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Financial Management for Hospitality & Tourism', 'TCHT1-UC 1100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hotel & Tourism Accounting', 'TCHT1-UC 1120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hospitality and Travel Technology and Innovation', 'TCHT1-UC 1130', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Service Operations', 'TCHT1-UC 1140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Data Analytics and Visualization', 'TCHT1-UC 1150', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Resource Management', 'TCHT1-UC 1200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hospitality & Tourism Sales & Marketing', 'TCHT1-UC 1300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Leadership in the Hospitality Industry', 'TCHT1-UC 1350', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hospitality & Tourism Law', 'TCHT1-UC 1400', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research Methods', 'TCHT1-UC 1500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business Fundamentals', 'TCHT1-UC 1600', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Strategies for Academic Success', 'TCHT1-UC 1920', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship I', 'TCHT1-UC 2000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship II', 'TCHT1-UC 2001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship III', 'TCHT1-UC 2010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Hotel Operations Management', 'TCHT1-UC 3200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Managing Food and Beverage Operations', 'TCHT1-UC 3240', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Event Design & Production', 'TCHT1-UC 3255', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brand Management', 'TCHT1-UC 3265', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Strategic Pricing & Revenue Management', 'TCHT1-UC 3270', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Market Analysis', 'TCHT1-UC 3300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Planning, Design and Construction', 'TCHT1-UC 3310', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sports Tourism Development', 'TCHT1-UC 3430', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Placemaking and Destination Branding', 'TCHT1-UC 3460', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tourism Planning and Policy', 'TCHT1-UC 3470', NULL, 'sp2026') ON CONFLICT DO NOTHING;

COMMIT;
