BEGIN;

INSERT INTO classes (name, code, section, semester) VALUES ('Music History I', 'MPATC-UE 1067', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music History II: Baroque & Classical', 'MPATC-UE 1068', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music History III', 'MPATC-UE 1077', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music History IV: Twentieth Century', 'MPATC-UE 1078', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music History: Music & Protest', 'MPATC-UE 1079', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Composer’s Ensemble', 'MPATC-UE 1080', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music of East and Southeast Asia, Past and Present', 'MPATC-UE 1086', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Orchestration I', 'MPATC-UE 1088', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Conducting: Foundations', 'MPATC-UE 1091', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Conducting: Intermediate Instrumental', 'MPATC-UE 1093', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Conducting: Advanced Musical Theater', 'MPATC-UE 1094', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Soundscapes: A Survey of Musical Traditions', 'MPATC-UE 1123', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar in Composition: Advanced Scoring Toolkit', 'MPATC-UE 1132', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mixing in the Digital Audio Workstation', 'MPATC-UE 1135', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Songwriters Forum', 'MPATC-UE 1190', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Composition Undergraduate Capstone', 'MPATC-UE 1192', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Songwriting History and Criticism: 14 Songs II', 'MPATC-UE 1196', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Composing for Film and Multimedia', 'MPATC-UE 1248', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Fundamentals', 'MPATC-UE 1300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theory & Practice I: Global Approaches to Music', 'MPATC-UE 1301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Aural Skills I: Global Approaches to Music', 'MPATC-UE 1302', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theory & Practice II: Tonal Harmony & Voice Leading', 'MPATC-UE 1311', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theory & Practice II: Popular Music', 'MPATC-UE 1312', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Aural Skills II: Tonal Harmony & Voice Leading', 'MPATC-UE 1321', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Aural Skills II: Popular Music', 'MPATC-UE 1322', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Theory & Practice: 20th and 21st Century Music', 'MPATC-UE 1332', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Theory & Practice: Non-Western Music', 'MPATC-UE 1333', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Theory & Practice: Counterpoint in the Digital Age', 'MPATC-UE 1334', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Theory & Practice: Popular Music', 'MPATC-UE 1335', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Aural Skills: 20th and 21st Century', 'MPATC-UE 1342', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Aural Skills: Sight-Singing', 'MPATC-UE 1343', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Aural Skills: Popular Music Transcription', 'MPATC-UE 1344', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Composer’s Forum', 'MPATC-UE 1424', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Film Music: Historical Aesthetics/Perspectives', 'MPATC-UE 1500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Narrative and Theatrical Songwriting', 'MPATC-UE 1501', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Drums, Drum Machines and DAWs', 'MPATC-UE 1634', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Composition (Private Lessons)', 'MPATC-UE 9021', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Hist II: Baroque & Class', 'MPATC-UE 9068', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro Music Therapy', 'MPAMT-UE 1046', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'NUTR-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food Microbiology & Sanitation', 'NUTR-UE 1023', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food Production and Management', 'NUTR-UE 1052', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Nutritional Biochemistry: Energy and Macronutrients', 'NUTR-UE 1064', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Nutritional Biochemistry: Micronutrients', 'NUTR-UE 1065', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Human Physiology', 'NUTR-UE 1068', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Current Research in Nutrition', 'NUTR-UE 1117', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food Science & Tech', 'NUTR-UE 1184', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Clinical Nutrition Assessment Intervention', 'NUTR-UE 1185', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Nutrition and Health', 'NUTR-UE 119', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fieldwork', 'NUTR-UE 1198', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theories & Techniques of Nutrition Ed Counseling', 'NUTR-UE 120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Community Nutrition', 'NUTR-UE 1209', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Diet Assessment and Planning', 'NUTR-UE 1260', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Nutrition and Life Cycle', 'NUTR-UE 1269', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Foods and Food Science', 'NUTR-UE 85', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food Management Theory', 'NUTR-UE 91', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Global Issues in Nutrition', 'NUTR-UE 9187', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Orientation to O.T.', 'OT-UE 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Anatomy', 'OT-UE 1001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Anatomy Lab', 'OT-UE 1002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Learning and The Meaning of Life', 'PHED-UE 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Learning and The Meaning of Life', 'PHED-UE 9010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Literature, Art, and the Path of Life', 'PHED-UE 9017', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching Science Education:Middle School', 'SCIED-UE 1911', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching Science Education:High School', 'SCIED-UE 1922', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Science in Our Lives: Environmental Issues', 'SCIED-UE 212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Science in Our Lives: Human Health & Disease', 'SCIED-UE 213', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Science in Our Lives: Origins & Possible Futures', 'SCIED-UE 214', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Science in Our Lives: Facts and Lies in the Name of Science', 'SCIED-UE 218', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Key Debates in U.S. History', 'SOCED-UE 1073', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Howard Zinn & People''s History of the US', 'SOCED-UE 1075', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Trnds/Prob Sec Soc St Ed', 'SOCED-UE 1135', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Social Studies I', 'SOCED-UE 1911', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Social Studies II', 'SOCED-UE 1922', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Teach Stu With Disabili in General Ed Class Rm', 'SPCED-UE 1005', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles & Strategies for Teaching Students with High Incidence Disabilities', 'SPCED-UE 1007', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles & Strategies for Teaching Students with Low Incidence Disabilities', 'SPCED-UE 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Assessment & Intervention in Special Education', 'SPCED-UE 1035', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Learning Environments, Behavior, and Students with Disabilities', 'SPCED-UE 1161', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Childhood Special Education I', 'SPCED-UE 1504', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Childhood Special Education IV', 'SPCED-UE 1901', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Early Childhood Special Education II', 'SPCED-UE 1903', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Early Childhood Special Education IV', 'SPCED-UE 1904', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Foundations of Spec Educ', 'SPCED-UE 83', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('New Student Seminar', 'SAHS-UE 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First Year Leadership Seminar', 'SAHS-UE 1011', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('AnBryce Undergraduate Scholars Seminar', 'SAHS-UE 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to the Galleries and Museums of New York', 'ART-UE 1002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art Education in Community Settings', 'ART-UE 1005', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Drawing I for Non-Majors', 'ART-UE 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Studio Art', 'ART-UE 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Drawing II for Non-Majors', 'ART-UE 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Painting I for Non-Majors', 'ART-UE 103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Painting II for Non-Majors', 'ART-UE 104', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Printmaking I for Non-Majors', 'ART-UE 105', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('2D Fundamentals I', 'ART-UE 107', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Drawing', 'ART-UE 1114', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Painting', 'ART-UE 1116', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Printmaking', 'ART-UE 1118', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Drawing', 'ART-UE 1180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Painting', 'ART-UE 1181', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Printmaking', 'ART-UE 1182', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sculpture Methods & Materials: Casting and Moldmaking', 'ART-UE 1232', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Sculpture', 'ART-UE 1280', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Video', 'ART-UE 1318', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Photography', 'ART-UE 1380', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Design Studio for Non-Majors', 'ART-UE 1421', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ceramics', 'ART-UE 1517', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Crafts Arts', 'ART-UE 1580', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Glass', 'ART-UE 1582', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Ceramics', 'ART-UE 1584', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Studio II', 'ART-UE 1902', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('BFA Individual Critique and Review', 'ART-UE 1905', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interdisciplinary Proj: Photo/Video, Performance/Installation', 'ART-UE 1995', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sculpture I for Non-Majors', 'ART-UE 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('3D Fundamentals II', 'ART-UE 212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interdisciplinary Art Practice II', 'ART-UE 23', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Photography I for Non Majors', 'ART-UE 300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photography I for Non-Majors', 'ART-UE 301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photography II for Non-Majors', 'ART-UE 302', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Art I for Non-Majors', 'ART-UE 303', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Video Art I for Non-Majors', 'ART-UE 305', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('4D Fundamentals I', 'ART-UE 314', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Design I for Non-Majors', 'ART-UE 401', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Design II for Non-Majors', 'ART-UE 402', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Metalsmithing I for Non-Majors', 'ART-UE 501', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ceramics I for Non-Majors', 'ART-UE 503', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Color I', 'ART-UE 90', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Visual Arts Praxis', 'ART-UE 900', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Interdisciplinary Art Practice', 'ART-UE 9022', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Drawing I for Non-Majors', 'ART-UE 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photography I for Non-Majors', 'ART-UE 9301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projects in Digital Art Sound Art', 'ART-UE 9381', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Inquiries Into Teaching & Learning I', 'TCHL-UE 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Honors Seminar in Teaching & Learning II', 'TCHL-UE 1091', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Curriculum: Entrepreneurship and Fundraising', 'TCHL-UE 1153', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Drug, Alcohol Ed/Child Abuse ID/School Violence/DASA:', 'TCHL-UE 1999', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Thinking Qualitatively', 'TCHL-UE 30', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Dilemmas: Race, Inequality, and the Unfulfilled', 'TCHL-UE 41', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Field Observ in Schools and Other Educ Settings', 'TCHL-UE 5', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching World Language Education: Middle/High School II', 'WLGED-UE 1922', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Being Digital: How the Internet Works/Why It Is Important', 'EDCT-UE 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Information Technology & Artificial Intelligence', 'EDCT-UE 1041', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creativity and Artificial Intelligence', 'EDCT-UE 1042', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Academic English for Liberal Studies II', 'AELS-UF 1002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Global Topics Transnational Migration, Identity, & Citizenship', 'AGT-UF 9301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Writing Studio Autobiography, Memoir, and the Global Self', 'AWS-UF 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('African Cultures', 'AFGC-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Arts and Cultures across Antiquity', 'ACA-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Arts and Cultures of Modernity', 'ACM-UF 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Arts and Cultures of Modernity', 'ACM-UF 9201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Caribbean Cultures', 'CAGC-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Writing Experiments', 'CWE-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Writing Studio', 'CWS-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dean''s Circle Research Seminar', 'DC-UF 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('East Asian Cultures', 'EAGC-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Macroeconomics', 'ECI-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Macroeconomics', 'ECI-UF 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Microeconomics', 'ECII-UF 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Environmental Studies', 'ENSTU-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Environmental Studies', 'ENSTU-UF 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fieldwork Seminar', 'FWS-UF 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fieldwork Seminar', 'FWS-UF 9201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Topics: (...)', 'GT-UF 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Topics Transnational Feminism after Global Sisterhood', 'GT-UF 9201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Works and Society: Antiquity', 'GWA-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Works and Society: Modernity', 'GWM-UF 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of The Universe', 'HOU-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Fieldwork', 'IF-UF 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'IND-UF 301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Indigenous Cultures', 'INGC-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Latin American Cultures', 'LAGC-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Latin American Cultures', 'LAGC-UF 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Life Science', 'LISCI-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Middle Eastern Cultures', 'MEGC-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Middle Eastern Cultures', 'MEGC-UF 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar (...)', 'SCAI-UF 401', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('South Asian Cultures', 'SAGC-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('South Asian Cultures', 'SAGC-UF 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sustainability Science: A History of Biodiversity and Climate Change', 'SUSCI-UF 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Liberal Studies Elective Interdependent: Professional Editing & Publishing', 'ELEC-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Liberal Studies Elective I (...)', 'ELEC-UF 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Impact Scholars Program', 'ELEC-UF 103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Liberal Studies Elective', 'ELEC-UF 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing as Critical Inquiry', 'WRCI-UF 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing as Critical Inquiry', 'WRCI-UF 9102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing as Exploration', 'WREX-UF 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing as Exploration', 'WREX-UF 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;

COMMIT;
