BEGIN;

INSERT INTO classes (name, code, section, semester) VALUES ('Physical Science: Einstein''s Universe', 'CORE-UA 204', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Physical Science: Quarks to Cosmos', 'CORE-UA 209', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Physical Science: How Things Work', 'CORE-UA 214', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Life Science: Human Genetics', 'CORE-UA 303', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Life Science: Human Origins', 'CORE-UA 305', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Life Science: Brain and Behavior', 'CORE-UA 306', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Texts & Ideas: Topics (...)', 'CORE-UA 400', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Texts & Ideas: Antiquity & The Enlightenment', 'CORE-UA 403', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Texts & Ideas: Antiquity & The 19th Century', 'CORE-UA 404', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Topics (...)', 'CORE-UA 500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Islamic Societies', 'CORE-UA 502', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Caribbean', 'CORE-UA 509', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures and Contexts: Russia Between East and West', 'CORE-UA 510', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Ancient Israel', 'CORE-UA 514', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Muslim Spain', 'CORE-UA 527', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Modern Israel', 'CORE-UA 537', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Korea', 'CORE-UA 543', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Egypt of The Pharaohs', 'CORE-UA 545', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Pagan Europe', 'CORE-UA 553', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Topics Making the Ancient Mediterranean World', 'CORE-UA 700', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Architecture', 'CORE-UA 725', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Sounds', 'CORE-UA 730', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture:Performance', 'CORE-UA 740', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Film', 'CORE-UA 750', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Life Science: Brain and Behavior', 'CORE-UA 9306', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Texts and Ideas: (...)', 'CORE-UA 9400', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Latin America', 'CORE-UA 9515', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: The Black Atlantic', 'CORE-UA 9534', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Cultures & Contexts: Spain', 'CORE-UA 9544', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultures & Contexts: Multicultural France', 'CORE-UA 9547', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Culture and Context: Italy', 'CORE-UA 9554', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Topics Native Arts in Contemporary America', 'CORE-UA 9700', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Images', 'CORE-UA 9720', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: (...)', 'CORE-UA 9722', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Museums in Field Study:', 'CORE-UA 9723', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Music in Prague Field Study', 'CORE-UA 9731', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Opera in Florence', 'CORE-UA 9732', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Expressive Culture: Film', 'CORE-UA 9750', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Punjabi II', 'COLU-UA 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Punjabi II', 'COLU-UA 104', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Bengali II', 'COLU-UA 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Sanskrit II', 'COLU-UA 122', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Sanskrit II', 'COLU-UA 124', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Swahili II', 'COLU-UA 134', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Swahili II', 'COLU-UA 136', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Bengali II', 'COLU-UA 14', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Ukrainian II', 'COLU-UA 172', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Ukrainian II', 'COLU-UA 174', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Ukrainian II through Literature, Media and Politics', 'COLU-UA 176', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Yoruba II', 'COLU-UA 204', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Bosnian/Croatian/Serbian I', 'COLU-UA 21', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Bosnian/Croatian/Serbian II', 'COLU-UA 22', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Bosnian/Croatian/Serbian II', 'COLU-UA 24', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Bosnian/Croatian/Serbian II', 'COLU-UA 26', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Hungarian II', 'COLU-UA 74', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Indonesian II', 'COLU-UA 82', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Indonesian II', 'COLU-UA 84', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Polish II', 'COLU-UA 92', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Polish II', 'COLU-UA 94', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Polish II', 'COLU-UA 96', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Translation Theory: Comparative Approaches and Case Studies', 'COLIT-UA 121', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Studies in Prose Genres: The Personal Essay in World Literature', 'COLIT-UA 125', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Classical Literature & Philosophy: Ancient Presence in 19th & 20th Centuries', 'COLIT-UA 160', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tpcs in Italian Culture: Technology, Italian Style', 'COLIT-UA 173', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theory Seminar Forgetting in Literature and Theory', 'COLIT-UA 200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Film & Literature: African Cinema and Literature', 'COLIT-UA 300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics Postcolonial Adaptations', 'COLIT-UA 550', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Modern Chinese Fiction', 'COLIT-UA 723', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: The Bible as Literature', 'COLIT-UA 800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'COLIT-UA 852', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Yiddish Literature and Translation', 'COLIT-UA 866', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Studies in Prose Genres Post-colonial Readings of Classic Texts', 'COLIT-UA 9125', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Kafka and His Contexts', 'COLIT-UA 9136', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in 19th Century Lit Italy & Italians in Engl Lit from Romantic To Mod', 'COLIT-UA 9180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tpcs in Asian Std: Historical Epics of China and Japan', 'COLIT-UA 950', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Storytelling: Myth, Folklore, Literature', 'COLIT-UA 951', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Leopardi: Archaism, Revolt. & Self', 'COLIT-UA 972', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics:', 'COLIT-UA 975', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'COLIT-UA 997', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study: Internship', 'COLIT-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Computer Science', 'CSCI-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Data Structures', 'CSCI-UA 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Computer Programming (No Prior Experience)', 'CSCI-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Computer Systems Org', 'CSCI-UA 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Operating Systems', 'CSCI-UA 202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Computer Programming (Limited Prior Experience)', 'CSCI-UA 3', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Basic Algorithms', 'CSCI-UA 310', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Computer Simulation', 'CSCI-UA 330', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics of General Interest: (...)', 'CSCI-UA 380', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Programming Tools for the Data Scientist', 'CSCI-UA 381', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Web Design and Computer Principles', 'CSCI-UA 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Numerical Computing', 'CSCI-UA 421', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Agile Software Development and DevOps', 'CSCI-UA 430', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theory of Computation', 'CSCI-UA 453', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Applied Internet Technology', 'CSCI-UA 467', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Natural Language Processing', 'CSCI-UA 469', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Object Oriented Programming', 'CSCI-UA 470', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Artificial Intelligence', 'CSCI-UA 472', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Machine Learning', 'CSCI-UA 473', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Software Engineering', 'CSCI-UA 474', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Predictive Analytics', 'CSCI-UA 475', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Processing Big Data for Analytics Applications', 'CSCI-UA 476', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Data Management and Analysis', 'CSCI-UA 479', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics: (...)', 'CSCI-UA 480', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Undergraduate Research', 'CSCI-UA 521', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Database Design and Implementation', 'CSCI-UA 60', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Web Development and Programming', 'CSCI-UA 61', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Computer Science', 'CSCI-UA 898', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Web Design and Computer Principles', 'CSCI-UA 9004', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Web Development and Programming', 'CSCI-UA 9061', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Computer Science', 'CSCI-UA 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Artificial Intelligence', 'CSCI-UA 9472', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Machine Learning', 'CSCI-UA 9473', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Data Management and Analysis', 'CSCI-UA 9479', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'CSCI-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Writing: Intro Prose & Poetry', 'CRWRI-UA 815', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Fiction Workshop', 'CRWRI-UA 816', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Poetry Workshop', 'CRWRI-UA 817', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Fiction Workshop', 'CRWRI-UA 820', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Creative Nonfiction Workshop', 'CRWRI-UA 825', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Poetry Workshop', 'CRWRI-UA 830', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Creative Nonfiction Workshop', 'CRWRI-UA 850', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intensive Seminar in Fiction', 'CRWRI-UA 861', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('IntensiveSeminar in Poetry', 'CRWRI-UA 862', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intensive Seminar in Creative Nonfiction', 'CRWRI-UA 863', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Writing', 'CRWRI-UA 9815', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Survey in Data Science', 'DS-UA 100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Data Science I', 'DS-UA 111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Data Science II', 'DS-UA 112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Causal Inference', 'DS-UA 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Responsible Data Science', 'DS-UA 202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Machine Learning for Climate Change', 'DS-UA 205', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics in Data Science Linear Regression Models', 'DS-UA 300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Topics in Data Science Introduction to Deep Learning and LLM based Gener', 'DS-UA 301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Survey in Data Science', 'DS-UA 9100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Principles of Data Science I', 'DS-UA 9111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Causal Inference', 'DS-UA 9201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hist of Drama & Theatre II', 'DRLIT-UA 111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Spectacle and Surveillance', 'DRLIT-UA 175', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'DRLIT-UA 185', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Shakespeare', 'DRLIT-UA 225', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Colloq: Shakespeare', 'DRLIT-UA 230', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Colloquium: (...)', 'DRLIT-UA 244', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Major Playwrights: Fornes', 'DRLIT-UA 254', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Afro-American Drama', 'DRLIT-UA 255', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Performance Studies (...)', 'DRLIT-UA 301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Film and Literature: Antifascist Literature and Film', 'DRLIT-UA 306', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in International Cinema (...)', 'DRLIT-UA 524', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Drama & Performance in London', 'DRLIT-UA 9133', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Shakespeare and the Elizabethan Stage: Text and Performance', 'DRLIT-UA 9412', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Int''l Cinema', 'DRLIT-UA 9524', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Spanish Culture through Cinema (in Spanish)', 'DRLIT-UA 9551', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Dramatic Lit', 'DRLIT-UA 971', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'DRLIT-UA 981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Chinese I', 'EAST-UA 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Chinese II', 'EAST-UA 202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Chinese I', 'EAST-UA 203', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Chinese II', 'EAST-UA 204', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Chinese I', 'EAST-UA 205', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Chinese II', 'EAST-UA 206', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Learning Chinese through Media', 'EAST-UA 211', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Readings in Chinese Poetry II', 'EAST-UA 214', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Learning Chinese through Reading and Writing', 'EAST-UA 216', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Readings in Chinese Culture II', 'EAST-UA 222', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Politico-Philosophical Texts in Classical Chinese', 'EAST-UA 223', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Classical Chinese', 'EAST-UA 226', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Chinese for Advanced Beginners', 'EAST-UA 231', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Chinese for Advanced Beginners', 'EAST-UA 232', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Japanese I', 'EAST-UA 247', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Japanese II', 'EAST-UA 248', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Japanese I', 'EAST-UA 249', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Japanese II', 'EAST-UA 250', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Japanese I', 'EAST-UA 252', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Japanese II', 'EAST-UA 253', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Korean I', 'EAST-UA 254', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Korean II', 'EAST-UA 255', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Korean I', 'EAST-UA 256', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Korean II', 'EAST-UA 257', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Korean I', 'EAST-UA 258', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Korean II', 'EAST-UA 259', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Readings in Japanese Literature I', 'EAST-UA 264', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Japanese Reading Practice', 'EAST-UA 271', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Korean for Advanced Learners', 'EAST-UA 281', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Korean for Advanced Learners', 'EAST-UA 282', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Structure of Korean', 'EAST-UA 283', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Readings in Modern Korean', 'EAST-UA 299', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Chinese Cultural Revolution in the Global Context', 'EAST-UA 526', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Chinese Hist (...)', 'EAST-UA 551', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Mapping the Soundscape of Popular Music Cultures i', 'EAST-UA 569', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultural Insights of Business Communication', 'EAST-UA 603', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultural Insights of Cross-Border Business', 'EAST-UA 604', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Historical Epics of China and Japan', 'EAST-UA 726', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Chinese Fiction', 'EAST-UA 732', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Korea & The Korean Diaspora', 'EAST-UA 735', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vietnam: the war & its history', 'EAST-UA 737', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('East Asian Art II: China, Korea, Japan to 1000 Ce', 'EAST-UA 9092', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Asian Studies: East Asian Art & Civilizations', 'EAST-UA 950', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Korean Studies Very Contemporary Korean Literature', 'EAST-UA 951', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Chinese Studies (...)', 'EAST-UA 952', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Japanese Studies (...)', 'EAST-UA 953', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'EAST-UA 981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'EAST-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Macroeconomics', 'ECON-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interm Microeconomics', 'ECON-UA 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Microeconomic Analysis', 'ECON-UA 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interm Macroeconomics', 'ECON-UA 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Macroeconomic Analysis', 'ECON-UA 13', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Statistics (P)', 'ECON-UA 18', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Microeconomics', 'ECON-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Analytical Statistics', 'ECON-UA 20', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ethics and Economics', 'ECON-UA 207', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Urban Economics', 'ECON-UA 227', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Money and Banking', 'ECON-UA 231', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Economics (P)', 'ECON-UA 238', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Econometrics', 'ECON-UA 266', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Game Theory (T)', 'ECON-UA 310', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Industrial Organization', 'ECON-UA 316', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Economic Development', 'ECON-UA 323', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Economics: Finance', 'ECON-UA 336', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Political Economy (T)', 'ECON-UA 345', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Labor Economics', 'ECON-UA 351', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Public Economics', 'ECON-UA 353', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Health Economics', 'ECON-UA 354', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experimental Economics', 'ECON-UA 360', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Micro Theory (T)', 'ECON-UA 365', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Markets with Frictions', 'ECON-UA 366', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Macroeconomics (T)', 'ECON-UA 367', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Financial Economics (P)', 'ECON-UA 368', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Econometrics (P,T)', 'ECON-UA 402', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Thesis I', 'ECON-UA 450', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Macroeconomics', 'ECON-UA 9001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Microeconomics', 'ECON-UA 9002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interm Microeconomics', 'ECON-UA 9010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interm Macroeconomics', 'ECON-UA 9012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Economics of European Integration', 'ECON-UA 9219', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Money & Banking', 'ECON-UA 9231', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Economics', 'ECON-UA 9238', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Economics', 'ECON-UA 997', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'ECON-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to the Study of Literature', 'ENGL-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Literatures in English I: Medieval and Early Modern Literatures', 'ENGL-UA 111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Literatures in English II: Literatures of the British Isles and British Empire 1660-1900', 'ENGL-UA 112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Literatures in English III: American Literatures to 1900', 'ENGL-UA 113', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Literatures in English IV: Twentieth and Twenty-first Century Literatures', 'ENGL-UA 114', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Drama & Theatre II', 'ENGL-UA 126', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Reading as a Writer', 'ENGL-UA 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('18th and 19th Century African American Lit', 'ENGL-UA 250', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'ENGL-UA 252', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Old English Language & Literature', 'ENGL-UA 315', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The English Renaissance', 'ENGL-UA 400', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Shakespeare', 'ENGL-UA 410', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Colloq: Shakespeare', 'ENGL-UA 415', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('English Drama to 1642', 'ENGL-UA 420', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Jane Austen', 'ENGL-UA 511', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Colloquium: The Golden Age of English Lit', 'ENGL-UA 625', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Colloquium', 'ENGL-UA 700', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Major Texts in Critical Theory', 'ENGL-UA 712', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italian-American Life in Literature', 'ENGL-UA 724', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Readings in Contemporary Literary Theory', 'ENGL-UA 735', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Irish Lit: (...)', 'ENGL-UA 761', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Latina/o Literature', 'ENGL-UA 775', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Postcolonial Studies', 'ENGL-UA 780', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'ENGL-UA 800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Writing Capstone Project', 'ENGL-UA 910', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to the Study of Literature', 'ENGL-UA 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creative Writing Capstone Colloquium', 'ENGL-UA 911', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Literatures in English II: Literatures of the British Isles and British Empire 1660-1900', 'ENGL-UA 9112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mod Drama & Performance in London', 'ENGL-UA 9133', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('World Literature: Reading Down Under', 'ENGL-UA 9164', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing London', 'ENGL-UA 9182', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Reading as a Writer', 'ENGL-UA 9201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Honors Thesis', 'ENGL-UA 925', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Honors Colloquium', 'ENGL-UA 926', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Shakespeare and the Elizabethan Stage: Text and Performance', 'ENGL-UA 9412', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar: Medieval Literature Global Medievalisms', 'ENGL-UA 950', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar: 18th-Century British Literature Reading Jane Austen Reading', 'ENGL-UA 953', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('English Novel in The 19th Century', 'ENGL-UA 9530', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar: 19th-Century American Literature Emily Dickinson', 'ENGL-UA 961', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar: African American Literature Literary Friendships', 'ENGL-UA 963', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar: Genre Studies Repertoires of Social Movement Writing', 'ENGL-UA 972', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar: Interdisciplinary Study Love Stories and Love Sicknesses', 'ENGL-UA 973', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar: Poetry and Poetics SOME CONTEMPORARY POETRIES', 'ENGL-UA 974', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'ENGL-UA 981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Contemporary Literature Lab Greene St. Review', 'ENGL-UA 995', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'ENGL-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mentoring Program Course', 'ENGL-UA 999', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Contemporary Literature Lab Reading for Dear Life', 'ENGL-UA 9995', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Environment & Society', 'ENVST-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Topics: (...)', 'ENVST-UA 300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('NY Underground', 'ENVST-UA 327', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of United States Environmental Policy', 'ENVST-UA 423', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Urban Environmentalism', 'ENVST-UA 431', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Environmental Governance', 'ENVST-UA 435', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Animals, & The Environment', 'ENVST-UA 440', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Governing Disaster', 'ENVST-UA 444', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Environmental Values & Society (...)', 'ENVST-UA 450', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Environmental Humanities', 'ENVST-UA 700', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Environmental Studies', 'ENVST-UA 800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Environmental Studies Senior Seminar', 'ENVST-UA 900', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Climate Change', 'ENVST-UA 9226', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Green Horizons: Pathways to a Clean Energy Economy', 'ENVST-UA 9430', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Environmental Values & Society: Cities on the Move', 'ENVST-UA 9450', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business and the Environment', 'ENVST-UA 9465', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Environmental Social Movements', 'ENVST-UA 9481', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Seminar in Environmental Studies', 'ENVST-UA 950', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Admire, Fear, Compete. Europe and China, 19-20th C', 'EURO-UA 173', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'EURO-UA 174', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Criminalization of Migration and Solidarity', 'EURO-UA 292', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: A Global History of the Long 1990', 'EURO-UA 565', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('France and The European Union (in French)', 'EURO-UA 9122', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The European Union: History & Politics', 'EURO-UA 9123', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Italy', 'EURO-UA 9163', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Berlin''s Modern History & Culture: A European Perspective', 'EURO-UA 9225', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The German Intellectual Tradition: What is Power?', 'EURO-UA 9244', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Psychological Manipulation in Politics', 'EURO-UA 93', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Dissent in Central Europe:', 'EURO-UA 9301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: 20th Century European Capitalism', 'EURO-UA 9565', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'EURO-UA 981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in European Union Studies Europe''s Urban Youth in Times of EU Turbulence', 'EURO-UA 982', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'EURO-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing as Inquiry', 'EXPOS-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intersections: Writing for Scholarly Publics', 'EXPOS-UA 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing toward Linguistic Justice', 'EXPOS-UA 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Thesis Writing in the Humanities and Social Sciences', 'EXPOS-UA 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing Tutorial', 'EXPOS-UA 13', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('A Spectrum of Essays', 'EXPOS-UA 15', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Essay Writing for Science', 'EXPOS-UA 16', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing in Community', 'EXPOS-UA 17', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research, Writing, and Speaking in the Disciplines', 'EXPOS-UA 18', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Thinking across the University', 'EXPOS-UA 19', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Writing for Engineers', 'EXPOS-UA 22', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Writing Workshop Introduction', 'EXPOS-UA 3', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Writing Workshop I', 'EXPOS-UA 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Writing Workshop II', 'EXPOS-UA 9', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Complexities: Ocean', 'FYSEM-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Doctor''s Dilemma: Being Correct & Right', 'FYSEM-UA 379', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Political Theater', 'FYSEM-UA 476', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Crystallization in Life: Stories about Shells, Bones, and Kidney Stones', 'FYSEM-UA 714', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Happiness in Film', 'FYSEM-UA 781', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('DNA: From the Double Helix to Nanotechnology', 'FYSEM-UA 783', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Technology vs. Democracy: Can the American Experiment Survive American Innovation?', 'FYSEM-UA 788', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Italian Opera', 'FYSEM-UA 801', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Photography and New York', 'FYSEM-UA 831', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('New York Intellectuals, Past and Present', 'FYSEM-UA 836', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The University', 'FYSEM-UA 840', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Quantum Physics, Information and Communications: Why it can change the world and what''s next', 'FYSEM-UA 843', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Love and War. Epic and Romance from Classical Antiquity to Early Modernity', 'FYSEM-UA 847', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Indigenous Hip-Hop: A Global Language of Youth Activism and Resistance', 'FYSEM-UA 849', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Race After Fascism: Italian Literary Perspectives', 'FYSEM-UA 850', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Role of Humor in Social Protest', 'FYSEM-UA 855', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics (...)', 'FYSEM-UA 900', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elemen French Level I', 'FREN-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intens Elementary French', 'FREN-UA 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Spoken Contemp French I', 'FREN-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French Phonetics', 'FREN-UA 103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Written Contemporary French', 'FREN-UA 105', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate French I', 'FREN-UA 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French for International Relations', 'FREN-UA 113', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate French II', 'FREN-UA 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Approaches to French History', 'FREN-UA 163', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elem French Level II', 'FREN-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intens Intermed French', 'FREN-UA 20', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Louisiana Immersion Program', 'FREN-UA 26', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Living in French in North America: An Immersion Program in New England and Quebec', 'FREN-UA 27', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French Grammar and Composition.', 'FREN-UA 30', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in French and Francophone Literature and Culture (...)', 'FREN-UA 865', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elem French I (in French)', 'FREN-UA 9001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elem French II', 'FREN-UA 9002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate French I', 'FREN-UA 9011', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate French II', 'FREN-UA 9012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French Grammar and Composition.', 'FREN-UA 9030', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French News in Conversation', 'FREN-UA 904', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Machines à écrire', 'FREN-UA 905', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Spoken Contemporary French', 'FREN-UA 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Written Contemporary French', 'FREN-UA 9105', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Acting French (in French)', 'FREN-UA 9109', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business French (in French)', 'FREN-UA 9110', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Advanced Contemporary French', 'FREN-UA 9112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('France and The European Union (in French)', 'FREN-UA 9122', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Approaches to French Literature in French', 'FREN-UA 9140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Versailles - Life as Art in the Age of Grandeur (in French)', 'FREN-UA 9150', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French and Francophone Women Writers', 'FREN-UA 935', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in French and Francophone Literature and Culture (...)', 'FREN-UA 965', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('France and Islam', 'FREN-UA 9806', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experimental Theatre Workshop', 'FREN-UA 9807', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Lost and Found: Expatriate Writers in Paris', 'FREN-UA 9808', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French Novel: the 20th and 21st Centuries', 'FREN-UA 9831', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Studies in Prose Genres: Postcolonial Readings of Classic Texts', 'FREN-UA 9833', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics (...)', 'FREN-UA 9865', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('German Occupation in French Literature and Cinema (in French)', 'FREN-UA 9902', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French News in Conversation', 'FREN-UA 9904', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French Phonetics Workshop', 'FREN-UA 9906', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar (...)', 'FREN-UA 992', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Gender and Sexuality in France (in French)', 'FREN-UA 9936', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Thesis', 'FREN-UA 995', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Lit Writing Workshop:Reading & Writing Paris (in Fren)', 'FREN-UA 9968', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'FREN-UA 997', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'FREN-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary German I', 'GERM-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('German Culture 1890-1989', 'GERM-UA 133', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to German Literature', 'GERM-UA 152', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary German II', 'GERM-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intensive Intermediate German', 'GERM-UA 20', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Storytelling: Myth, Folklore, Literature', 'GERM-UA 283', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in 20th Cent Lit: Kafka', 'GERM-UA 298', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate German I', 'GERM-UA 3', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Post 1945 German Lit', 'GERM-UA 369', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topcs in German Cinema: Contemporary German Film', 'GERM-UA 390', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate German II', 'GERM-UA 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Thesis', 'GERM-UA 500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary German I', 'GERM-UA 9001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary German II', 'GERM-UA 9002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate German I', 'GERM-UA 9003', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate German II', 'GERM-UA 9004', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intensive Elem German', 'GERM-UA 9010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intensive Intermediate German', 'GERM-UA 9020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced German Tutorial', 'GERM-UA 9091', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Composition/Conversation', 'GERM-UA 9111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to German Literature', 'GERM-UA 9152', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Berlin''s Modern History & Culture: A European Perspective', 'GERM-UA 9225', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The German Intellectual Tradition', 'GERM-UA 9244', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('German Theater of the 20th Century: History & Practice', 'GERM-UA 9290', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('20th and 21st Century German Prose Contemporary Literature on the Refugee Crisis', 'GERM-UA 9366', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'GERM-UA 977', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'GERM-UA 990', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Honors Seminar', 'GERM-UA 999', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Hebrew I', 'HBRJD-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ancient Near Eastern Mythology', 'HBRJD-UA 125', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Anti-Semitism: Then and Now | Antisemitism Then and Now', 'HBRJD-UA 137', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Land of Israel Through The Ages', 'HBRJD-UA 141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Judaic Studies Jews and Food', 'HBRJD-UA 177', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Hebrew II', 'HBRJD-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Bible as Literature', 'HBRJD-UA 23', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Hebrew I', 'HBRJD-UA 3', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Hebrew II', 'HBRJD-UA 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creating a Good Society: Christian and Jewish Perspectives', 'HBRJD-UA 428', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Yiddish Literature and Translation', 'HBRJD-UA 664', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Hebrew: Israeli Communications Media', 'HBRJD-UA 73', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern American Jewish Literature and Culture', 'HBRJD-UA 779', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Readings in Talmud (in Hebrew) READINGS IN TALMUD (IN HEBREW): Sanhedrin 2', 'HBRJD-UA 784', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Monsters and Jewish Modernity', 'HBRJD-UA 90', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Hebrew I', 'HBRJD-UA 9001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Hebrew II', 'HBRJD-UA 9002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Hebrew I', 'HBRJD-UA 9003', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Hebrew II', 'HBRJD-UA 9004', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Hebrew I', 'HBRJD-UA 9011', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Adv Hebrew: Structure of Modern Hebrew', 'HBRJD-UA 9012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Jewish History', 'HBRJD-UA 9103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ancient Israel: History & Archaeology', 'HBRJD-UA 9118', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sexualities of the Middle East: A Cultural History', 'HBRJD-UA 9120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Languages of Israel', 'HBRJD-UA 9140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hist of the Jews in 20th Cent Europe: Comparative Perspectives-Italy, Germany/France', 'HBRJD-UA 9200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Israel Studies: Language, Discourse, and Political Conflict', 'HBRJD-UA 948', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Jewish Literature and Culture Kafka and His Afterlives', 'HBRJD-UA 965', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Israel Studies: History of the Palestinian - Israeli Conflict', 'HBRJD-UA 9948', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'HBRJD-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Mod Greek II', 'HEL-UA 104', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Modern Greek II', 'HEL-UA 106', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Modern Greek II', 'HEL-UA 108', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar On Modern Greek Culture (...)', 'HEL-UA 130', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theatre and Medicine: From the Greeks to the Modern Stage', 'HEL-UA 134', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Re-imagining Greek Tragedy', 'HEL-UA 140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Greek World: Alexander to Augustus', 'HEL-UA 243', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: The Greek Thinkers', 'HEL-UA 283', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'HEL-UA 980', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'HEL-UA 997', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Honors Seminar', 'HEL-UA 999', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('US Since 1865', 'HIST-UA 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'HIST-UA 112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Religious History Anti-Semitism: Then and Now', 'HIST-UA 117', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Europe', 'HIST-UA 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in French History', 'HIST-UA 141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Irish and New York', 'HIST-UA 180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Irish History: Ireland and America since 1922', 'HIST-UA 181', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Modern Ireland (1845-1922)', 'HIST-UA 183', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Greek World: Alexander to Augustus', 'HIST-UA 243', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('World of Medieval Magic', 'HIST-UA 262', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar: (...)', 'HIST-UA 275', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: A Global History of the Long 1990''s', 'HIST-UA 282', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'HIST-UA 283', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Russian History (...)', 'HIST-UA 292', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sem: Nativism and the Foreign Threat in US History', 'HIST-UA 295', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Protest and Rebellion in East Africa', 'HIST-UA 314', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: The Right to Vote: A History', 'HIST-UA 370', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar: (...)', 'HIST-UA 401', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Historical Consciousness in Latin America and the Caribbean', 'HIST-UA 454', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sem: Tpcs: Slavery In New York', 'HIST-UA 471', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Ottoman Empire and the World Around it', 'HIST-UA 515', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Chinese Cultural Revolution', 'HIST-UA 526', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Emergence of The Modern Middle East', 'HIST-UA 531', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: The Making of Mass Incarceration in America', 'HIST-UA 538', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar in Intellectual History Modern Arab Intellectual History', 'HIST-UA 552', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'HIST-UA 569', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in African History', 'HIST-UA 570', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Economic Thought', 'HIST-UA 592', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('US History Since 1945', 'HIST-UA 612', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'HIST-UA 629', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('America in The 60''S', 'HIST-UA 644', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Culture Wars', 'HIST-UA 651', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Asian History: History of Science, Technology, and Environment in', 'HIST-UA 654', NULL, 'sp2026') ON CONFLICT DO NOTHING;

COMMIT;
