BEGIN;

INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Science and Society', 'HIST-UA 66', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Europe and the Caribbean', 'HIST-UA 721', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vietnam: the war & its history', 'HIST-UA 737', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Drugs and Drug Wars', 'HIST-UA 741', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of The Andes', 'HIST-UA 753', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Women''S Hist Women and War', 'HIST-UA 820', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History in the Headlines', 'HIST-UA 9070', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('What is Islam?', 'HIST-UA 9085', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Everyday Technology in Early Modern China', 'HIST-UA 910', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italy During The Renaissance: Florence', 'HIST-UA 9123', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('A History of London', 'HIST-UA 9127', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comp Modern Societies: Pol & Soc in 20C Germany', 'HIST-UA 9133', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Twentieth Century US Hist in Film', 'HIST-UA 914', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in French History Modern France from the Revolution to the Present', 'HIST-UA 9141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Europe Since 1945', 'HIST-UA 9156', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Italy', 'HIST-UA 9168', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hist of Nationalism in Cent & Eastern Europe', 'HIST-UA 9176', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Black Lives Writing Washington, DC', 'HIST-UA 9185', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Imperialism: 19th & 20th Centuries', 'HIST-UA 9198', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Perspectives on the Civil War and the ''Recovery of Historical Memory'' in Spain', 'HIST-UA 9264', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('20th Century European Capitalism', 'HIST-UA 9272', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics History of the Jews in 20th Century Europe Best,', 'HIST-UA 9283', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Fascism', 'HIST-UA 9290', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Howard Zinn & People''s History of the US', 'HIST-UA 93', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Constitution', 'HIST-UA 9330', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Once Upon a Time: How to Read History', 'HIST-UA 94', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Immigration', 'HIST-UA 9452', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Germany and East Central Europe', 'HIST-UA 9514', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ancient Israel: History & Archaeology', 'HIST-UA 9524', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: The Italian South', 'HIST-UA 9538', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tpcs in Mideast History: Palestinian-Israeli Conflict', 'HIST-UA 9553', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cocoa and Gold: Ghana''s Development in Global Perspective', 'HIST-UA 9573', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: American Foreign Policy in the 20th Century', 'HIST-UA 9629', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Latin American Studies', 'HIST-UA 9744', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'HIST-UA 980', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar: Revolucion', 'HIST-UA 992', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Thesis/Tutorial', 'HIST-UA 996', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'HIST-UA 997', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Berlin''s Modern History Cult: A European Perspective', 'HIST-UA 9984', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ir Senior Seminar', 'INTRL-UA 990', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ir Senior Honors', 'INTRL-UA 991', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Irish Language Elementary II', 'IRISH-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Irish Language Intermediate II', 'IRISH-UA 103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Transatlantic Connections: Ireland and America since 1920', 'IRISH-UA 172', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Irish and New York', 'IRISH-UA 180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Modern Ireland II (1800-present)', 'IRISH-UA 183', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Irish Women Writers', 'IRISH-UA 627', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Irish Lit: Tpcs Irish Lit: Irish', 'IRISH-UA 761', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Arthurian Legend: Arthur and The Celts', 'IRISH-UA 800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Irish Literary, Visual, & Performing Arts', 'IRISH-UA 902', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'IRISH-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Italian I', 'ITAL-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intensive Elementary Italian', 'ITAL-UA 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italian Through Cinema', 'ITAL-UA 107', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Italian I', 'ITAL-UA 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Translation', 'ITAL-UA 110', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Readings in Modern Italian Literature', 'ITAL-UA 116', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Italian II', 'ITAL-UA 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Visual Poetry', 'ITAL-UA 152', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Italian Culture A Night at the Opera', 'ITAL-UA 171', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'ITAL-UA 172', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Ital Culture: (...)', 'ITAL-UA 173', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Italian II', 'ITAL-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intensive Intermediate Italian', 'ITAL-UA 20', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dante’s Divine Comedy in Context', 'ITAL-UA 269', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Italian Lit: Leopardi: Archaism, Revolt. & Self in the 1800s', 'ITAL-UA 285', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Review of Modern Italian', 'ITAL-UA 30', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italian-American Life in Literature', 'ITAL-UA 724', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Italian I', 'ITAL-UA 9001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Italian II', 'ITAL-UA 9002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Italian I', 'ITAL-UA 9011', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Italian II', 'ITAL-UA 9012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intensive Interm Italian', 'ITAL-UA 9020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Review of Modern Italian', 'ITAL-UA 9030', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Conversations in Italian', 'ITAL-UA 9101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Translation', 'ITAL-UA 9110', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Italian Culture Exploring the Landscape of Dante''s Divine Comedy', 'ITAL-UA 9171', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Culture of the City: Italian Urban Life', 'ITAL-UA 9403', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Academic Discourse in Italian', 'ITAL-UA 9500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italian Politics', 'ITAL-UA 9512', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Media Seminar: Media Activism and Democracy', 'ITAL-UA 9513', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Italy', 'ITAL-UA 9868', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Independent Study', 'ITAL-UA 990', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Journalistic Inquiry: The Written Word', 'JOUR-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Journalistic Inquiry: Multimedia', 'JOUR-UA 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Beat: (...)', 'JOUR-UA 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Methods and Practice: Narrative Podcasting', 'JOUR-UA 202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Methods & Practice: Photojournalism', 'JOUR-UA 203', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elective Reporting Tpcs: (...)', 'JOUR-UA 204', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Adv Reporting: (...)', 'JOUR-UA 301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Senior Seminar', 'JOUR-UA 352', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Investigating Journalism', 'JOUR-UA 50', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Journalism Ethics & First Amendment Law', 'JOUR-UA 502', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Journalism and Society: (...)', 'JOUR-UA 503', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Journalism as Lit: (...)', 'JOUR-UA 504', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Issues and Ideas: (...)', 'JOUR-UA 505', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Methods & Practice: (...)', 'JOUR-UA 9202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elective Reporting Tpcs: (...)', 'JOUR-UA 9204', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Production & Publication Travel Writing', 'JOUR-UA 9302', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Journalism Ethics & First Amendment Law', 'JOUR-UA 9502', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Journalism & Society: (...)', 'JOUR-UA 9503', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Issues & Ideas: Global Media Seminar: East-Central Europe', 'JOUR-UA 9505', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'JOUR-UA 980', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Individualized Studies', 'JOUR-UA 997', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Quechua I', 'LATC-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Quechua II', 'LATC-UA 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Quechua II', 'LATC-UA 104', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Haitian Creole II', 'LATC-UA 122', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Haitian Creole II', 'LATC-UA 124', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Mixteco II', 'LATC-UA 142', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Nahuatl II', 'LATC-UA 162', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Latin American and Caribbean History', 'LATC-UA 291', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Language in Latin America', 'LATC-UA 361', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics:', 'LATC-UA 455', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics:', 'LATC-UA 600', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Latin American and Caribbean History Art & Activism: Madrid’s Spanish-speaking Diaspora', 'LATC-UA 9291', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Culture, Identity and Politics in Latin America (In Spanish)', 'LATC-UA 9602', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Queer Cultures and Democracy', 'LATC-UA 9603', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Latin American Studies', 'LATC-UA 9604', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music of Latin America', 'LATC-UA 9606', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interamerica Relations: Latin America & The US', 'LATC-UA 9607', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Law and Society', 'LWSOC-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tpcs in Law & Society: (...)', 'LWSOC-UA 9251', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tpcs in Law & Society: Making an Exoneree', 'LWSOC-UA 951', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Language', 'LING-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research Seminar Language, Power, & Technology', 'LING-UA 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sound and Language', 'LING-UA 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Phonological Analysis', 'LING-UA 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Grammatical Analysis', 'LING-UA 13', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Language Change', 'LING-UA 14', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Language & Society', 'LING-UA 15', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Semantics', 'LING-UA 19', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Language in Latin America', 'LING-UA 30', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First Language Acquisition', 'LING-UA 59', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experimental Syntax and Semantics | Human Sentence Processing', 'LING-UA 61', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'LING-UA 981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'LING-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Discrete Mathematics', 'MATH-UA 120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Calculus I', 'MATH-UA 121', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Calculus II', 'MATH-UA 122', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Calculus III', 'MATH-UA 123', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Calculus III', 'MATH-UA 129', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematics for Economics I', 'MATH-UA 131', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematics for Economics II', 'MATH-UA 132', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematics for Economics III', 'MATH-UA 133', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Linear Algebra', 'MATH-UA 140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Computer Simulation', 'MATH-UA 144', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Linear Algebra', 'MATH-UA 148', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Probability & Statistics', 'MATH-UA 185', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Fluid Dynamics', 'MATH-UA 230', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Combinatorics', 'MATH-UA 240', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theory of Numbers', 'MATH-UA 248', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematics of Finance', 'MATH-UA 250', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Math Modeling | Introduction to Math Modeling', 'MATH-UA 251', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ordinary Diff Equations | Ordinary Differential Equations', 'MATH-UA 262', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Partial Diff Equations | Partial Differential Equations', 'MATH-UA 263', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Analysis', 'MATH-UA 325', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Analysis I', 'MATH-UA 328', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Analysis II', 'MATH-UA 329', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theory of Probability', 'MATH-UA 333', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematical Statistics', 'MATH-UA 334', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Theory of Probability', 'MATH-UA 338', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Algebra', 'MATH-UA 343', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Algebra II', 'MATH-UA 349', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Numerical Analysis', 'MATH-UA 352', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Linear and Nonlinear Optimization', 'MATH-UA 353', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Numerical Analysis', 'MATH-UA 358', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topology', 'MATH-UA 375', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Differential Geometry', 'MATH-UA 377', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Functions of a Complex Variable', 'MATH-UA 382', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors IV', 'MATH-UA 398', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Mathematics', 'MATH-UA 898', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Algebra, Trigonometry, and Functions', 'MATH-UA 9', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Calculus I', 'MATH-UA 9121', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematics for Economics II', 'MATH-UA 9132', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Linear Algebra', 'MATH-UA 9140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Probability & Statistics', 'MATH-UA 9185', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Mathematical Modeling', 'MATH-UA 9251', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Numerical Analysis', 'MATH-UA 9252', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Linear and Nonlinear Optimization', 'MATH-UA 9253', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MATH-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Art of the British and Irish Isles', 'MEDI-UA 250', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Arthurian Legend', 'MEDI-UA 800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Workshop in Medieval and Renaissance Studies II', 'MEDI-UA 902', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italy During The Renaissance: Florence', 'MEDI-UA 9123', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MEDI-UA 997', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Magic, Religion & Inquisition', 'MEDI-UA 9995', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Arabic I', 'MEIS-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Arabic II', 'MEIS-UA 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Arabic I', 'MEIS-UA 103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Arabic II', 'MEIS-UA 104', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Urdu II', 'MEIS-UA 302', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Urdu II', 'MEIS-UA 304', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Persian II', 'MEIS-UA 402', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Persian II', 'MEIS-UA 404', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Hindi II', 'MEIS-UA 406', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermed Hindi II', 'MEIS-UA 408', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Hindi II', 'MEIS-UA 410', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Turkish II', 'MEIS-UA 502', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermed Turkish II', 'MEIS-UA 504', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Islamic History al-Andalus', 'MEIS-UA 616', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ottoman Empire and the World Around It', 'MEIS-UA 650', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Modern Middle Eastern History Gender and Women in the Modern Middle East', 'MEIS-UA 688', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Emergence of The Modern Middle East', 'MEIS-UA 690', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Palestine, Zionism, & Israel', 'MEIS-UA 697', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Islam in the World', 'MEIS-UA 703', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Masterpieces of Medieval Arabic Literature in Translation', 'MEIS-UA 710', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('South Asian Literature', 'MEIS-UA 717', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Middle Eastern Literature Literatures of Afghanistan and Iran', 'MEIS-UA 720', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Women and Gender in Islam', 'MEIS-UA 728', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Arab Theatre & Film:', 'MEIS-UA 747', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Modern Middle Eastern Culture (...)', 'MEIS-UA 798', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Arabic II', 'MEIS-UA 9102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Arabic II', 'MEIS-UA 9104', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Languages of Israel', 'MEIS-UA 9150', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('What is Islam?', 'MEIS-UA 9691', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Islam & Spain', 'MEIS-UA 9707', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Middle East Politics: Palestinan-Israeli Conflict', 'MEIS-UA 9751', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MEIS-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to the Medical Humanities', 'MHUM-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Pandemics and Plagues', 'MHUM-UA 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in 20th Century Music Irish Music', 'MUSIC-UA 111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Musical Worlds of Yoko Ono', 'MUSIC-UA 178', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar: Aural Perception', 'MUSIC-UA 193', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elements of Music', 'MUSIC-UA 20', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Theory I', 'MUSIC-UA 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Theory II', 'MUSIC-UA 202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Performance & Analysis', 'MUSIC-UA 206', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Art of Listening:', 'MUSIC-UA 3', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ensemble IV The Afro-Cuban Creative Jazz Ensemble', 'MUSIC-UA 508', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics Seminar (...)', 'MUSIC-UA 901', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music of Latin America', 'MUSIC-UA 9155', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Grammy''s Afrobeats & Hiplife: African Contemporary Music', 'MUSIC-UA 9160', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'MUSIC-UA 981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MUSIC-UA 997', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MUSIC-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Neural Science', 'NEURL-UA 100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Behavioral and Integrative Neuroscience', 'NEURL-UA 220', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Behavioral & Integrative Neuroscience Lab', 'NEURL-UA 221', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics in Neural Science (...)', 'NEURL-UA 302', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Development and Dysfunction of the Nervous System', 'NEURL-UA 305', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('How to Build a Brain: From Channels to Networks', 'NEURL-UA 310', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Brain Health 101', 'NODEP-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics Seminar: Authoring Your NYU Story', 'NODEP-UA 100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: CAS Cornerstone Seminar', 'NODEP-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Leadership Development', 'NODEP-UA 601', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship: Seminar', 'NODEP-UA 981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research Seminar', 'NODEP-UA 9950', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Experiential Learning Seminar', 'NODEP-UA 9982', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in The History of Philosophy', 'PHIL-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Ethics & Pol Philosophy', 'PHIL-UA 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Metaphysics & Epistemology', 'PHIL-UA 103', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Greek Thinkers', 'PHIL-UA 122', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Early Modern European Philosophy', 'PHIL-UA 21', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Plato', 'PHIL-UA 22', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ethics and Society', 'PHIL-UA 3', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'PHIL-UA 302', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Life and Death', 'PHIL-UA 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Nature of Values', 'PHIL-UA 41', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creating a Good Society: Christian and Jewish Perspectives', 'PHIL-UA 428', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Minds and Machines', 'PHIL-UA 5', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Medical Ethics', 'PHIL-UA 50', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Logic', 'PHIL-UA 70', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Epistemology', 'PHIL-UA 76', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Philosophical Approaches to Race and Racism', 'PHIL-UA 8', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Philosophy of Language', 'PHIL-UA 85', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of French Philosophy', 'PHIL-UA 9026', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Existentialism and Phenomenology', 'PHIL-UA 9036', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Philosophy of Language', 'PHIL-UA 9085', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Philosoph Applications of Cognitive Science', 'PHIL-UA 93', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Philosophy of Physics', 'PHIL-UA 94', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematical Physics', 'PHYS-UA 106', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('General Physics I', 'PHYS-UA 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Electronics for Scientists I', 'PHYS-UA 110', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Experimental Physics', 'PHYS-UA 112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('General Physics II', 'PHYS-UA 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dynamics', 'PHYS-UA 120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Quantum Mechanics II', 'PHYS-UA 124', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Observational Astronomy', 'PHYS-UA 13', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Thermal & Statistical Physics', 'PHYS-UA 140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('General Relativity', 'PHYS-UA 170', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Fluid Dynamics', 'PHYS-UA 180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Universe: Its Nature and History', 'PHYS-UA 7', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introductory Experimental Physics II', 'PHYS-UA 72', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Experimental Physics II', 'PHYS-UA 74', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics in Physics: (...)', 'PHYS-UA 800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('General Physics II', 'PHYS-UA 9012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Physics II', 'PHYS-UA 93', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'PHYS-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Political Theory', 'POL-UA 100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Political Theory Seminar: (...)', 'POL-UA 195', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Power & Politics in America', 'POL-UA 300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Civil Liberties', 'POL-UA 332', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The U.S. Supreme Court', 'POL-UA 333', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Rule of Law', 'POL-UA 337', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Field Sem: (...)', 'POL-UA 395', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Politics', 'POL-UA 500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Field Seminar: (...)', 'POL-UA 595', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Sem: Ethnic Identity Politics & Democracy', 'POL-UA 596', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Politics', 'POL-UA 700', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('U.S. Foreign Policy', 'POL-UA 710', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Politics of Human Rights', 'POL-UA 711', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Int''L Political Economy', 'POL-UA 775', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internatl Field Sem: (...)', 'POL-UA 795', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Research Methods for Politics', 'POL-UA 850', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comp Modern Societies: Pol & Soc in 20C Germany', 'POL-UA 9133', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Spain and the European Union: Political and Economic Issues', 'POL-UA 9167', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Constitution', 'POL-UA 9330', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Private Influence in Public Policy', 'POL-UA 9341', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Politics of Western Europe', 'POL-UA 9509', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Honors II', 'POL-UA 951', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Western European Politics', 'POL-UA 9510', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italian Politics', 'POL-UA 9512', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('British Politics', 'POL-UA 9514', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Germany and East Central Europe', 'POL-UA 9515', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Fascism', 'POL-UA 9516', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The European Union: History & Politics', 'POL-UA 9521', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('France and The European Union Europe in Crisis (in French)', 'POL-UA 9523', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Economics of European Integration', 'POL-UA 9524', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Politics of Near & Middle East', 'POL-UA 9540', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Field Seminar: Understanding the European Union', 'POL-UA 9595', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('European-American Relations in The 21St Century | European-American in The 21St Century', 'POL-UA 9598', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Pol & Govt', 'POL-UA 970', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Political Economy of Developing Countries', 'POL-UA 9726', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Perspectives on Human Rights', 'POL-UA 9751', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interamerica Relations: Latin America & The US', 'POL-UA 9780', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Field Seminar: Political Institutions and Economic Policy', 'POL-UA 9795', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Readings & Research', 'POL-UA 990', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'POL-UA 994', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Politics: What is Freedom of Expression?', 'POL-UA 999', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'POL-UA 9994', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Portuguese for Spanish Speakers', 'PORT-UA 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study (spring)', 'PORT-UA 171', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Portuguese for Beginners II', 'PORT-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermed Portuguese I', 'PORT-UA 3', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics (in Portuguese) Brazil Through the Arts: Race, Gender and Social A', 'PORT-UA 300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermed Portuguese II', 'PORT-UA 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Portuguese Brazilian Culture and Society', 'PORT-UA 50', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Topics (in English) Anti-Colonial Art & Philosophy: Contemporary Black', 'PORT-UA 500', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Psychology', 'PSYCH-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Statistics for The Behavioral Sciences', 'PSYCH-UA 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Statistics and Data Analysis for Research in Psychology', 'PSYCH-UA 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Teaching in Psychology', 'PSYCH-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Seminar II', 'PSYCH-UA 201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Perception', 'PSYCH-UA 22', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cognitive Neuroscience', 'PSYCH-UA 25', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cognition', 'PSYCH-UA 29', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Personality', 'PSYCH-UA 30', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Spec Topics Psych: (...)', 'PSYCH-UA 300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Psychology', 'PSYCH-UA 32', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Developmental Psychology', 'PSYCH-UA 34', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Neuroscience', 'PSYCH-UA 35', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Lab in Personality & Social Psychology', 'PSYCH-UA 39', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Lab in Developmental Psychology', 'PSYCH-UA 40', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Lab in Infancy Research', 'PSYCH-UA 42', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Lab in Cognition and Perception', 'PSYCH-UA 46', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Abnormal Psychology', 'PSYCH-UA 51', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Psychological Science and Society Lab', 'PSYCH-UA 53', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Psycholinguistics', 'PSYCH-UA 56', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First Language Acquisition', 'PSYCH-UA 59', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Industrial Organizat''L Psychology', 'PSYCH-UA 62', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Political Psychology', 'PSYCH-UA 75', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Data Literacy for Psychology', 'PSYCH-UA 8', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Clinical Psychology', 'PSYCH-UA 81', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Psychology', 'PSYCH-UA 9001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cognition', 'PSYCH-UA 9029', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Personality', 'PSYCH-UA 9030', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Psychology', 'PSYCH-UA 9032', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Developmental Psychology', 'PSYCH-UA 9034', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Abnormal Psychology', 'PSYCH-UA 9051', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tutorial in Infancy Research', 'PSYCH-UA 992', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Supervised Reading', 'PSYCH-UA 993', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research Experience In Psychology', 'PSYCH-UA 996', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar', 'PUBPL-UA 800', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honor Thesis', 'PUBPL-UA 801', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ancient Near Eastern Mythology', 'RELST-UA 125', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Seminar: Religion and Law', 'RELST-UA 15', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Bible as Literature', 'RELST-UA 23', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creating a Good Society: Christian and Jewish Perspectives', 'RELST-UA 428', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics Televangelism', 'RELST-UA 650', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Women and Gender in Islam', 'RELST-UA 728', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Virgins Martyrs Monks & Saints: Early Christianity', 'RELST-UA 846', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('What is Islam?', 'RELST-UA 9085', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Religion, Pol & State in Compartv Perspectv', 'RELST-UA 9613', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Magic, Religion & Inquisition', 'RELST-UA 9671', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'RELST-UA 981', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics:', 'RELST-UA 983', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'RELST-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Russian II', 'RUSSN-UA 108', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Russian II', 'RUSSN-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Russian II', 'RUSSN-UA 4', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Russian Grammar & Composition II', 'RUSSN-UA 6', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics: (...)', 'RUSSN-UA 810', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Russian I', 'RUSSN-UA 9001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Russian II', 'RUSSN-UA 9002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Russian I', 'RUSSN-UA 9003', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Russian II', 'RUSSN-UA 9004', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Russian I', 'RUSSN-UA 9107', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Russian II', 'RUSSN-UA 9108', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Czech I', 'RUSSN-UA 9201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Czech II', 'RUSSN-UA 9202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Czech I', 'RUSSN-UA 9203', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Czech II', 'RUSSN-UA 9204', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Polish I', 'RUSSN-UA 9211', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Polish II', 'RUSSN-UA 9212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Polish I', 'RUSSN-UA 9213', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Polish II', 'RUSSN-UA 9214', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Russia and East-Central Europe', 'RUSSN-UA 9261', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'RUSSN-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social and Cultural Analysis 101', 'SCA-UA 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Swahili II', 'SCA-UA 122', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Social & Cultural Analysis: (...)', 'SCA-UA 18', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Africana Studies Slavery: histories, metaphors, and meanings', 'SCA-UA 180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Yoruba II', 'SCA-UA 183', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Justice Lab', 'SCA-UA 19', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Work, Labor, and Power', 'SCA-UA 221', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ethnicity & The Media', 'SCA-UA 232', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('America in the 60''s', 'SCA-UA 269', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'SCA-UA 280', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Filipino II', 'SCA-UA 322', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermediate Filipino II', 'SCA-UA 324', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elementary Cantonese II', 'SCA-UA 332', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intermed Cantonese II', 'SCA-UA 334', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Critical Indigenous Theory and Settler Colonialism', 'SCA-UA 372', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in A/P/A Studies: (...)', 'SCA-UA 380', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Queer Cultures', 'SCA-UA 450', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Contemporary Caribbean Women Writers', 'SCA-UA 481', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Latina Feminist Studies', 'SCA-UA 548', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Indigenous and Latinx Speculative Film and Fiction', 'SCA-UA 554', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Race and the Neoliberal Metropolis', 'SCA-UA 614', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Urban Environmentalism', 'SCA-UA 631', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Climate Change and Environmental Justice', 'SCA-UA 632', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Urban Studies', 'SCA-UA 680', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'SCA-UA 721', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'SCA-UA 744', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Amer Dilemmas: Race, Ineq, Unful Prm Pub Educ', 'SCA-UA 755', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Irish and New York', 'SCA-UA 758', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Shaping The Urban Environment', 'SCA-UA 762', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Latina/o Literature', 'SCA-UA 815', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Language in Latin America', 'SCA-UA 850', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Research Seminar (...)', 'SCA-UA 90', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Grammy''s Afrobeats & Hiplife: African Contemporary Music', 'SCA-UA 9120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Documenting The African City', 'SCA-UA 9124', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Africana Studies Race and Racialization in Italy', 'SCA-UA 9180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Black Lives Writing Washington DC', 'SCA-UA 9186', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Honors Thesis', 'SCA-UA 93', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Transnational Migration', 'SCA-UA 9616', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Culture of The City', 'SCA-UA 9620', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Connections: Berlin Spaces', 'SCA-UA 9634', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Black Capitalism and the Quest for Economic Freedom in America', 'SCA-UA 9700', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics Art & Activism: Madrid’s Spanish-speaking Diaspora', 'SCA-UA 9721', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: Revitalizing the American City', 'SCA-UA 9744', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Australian Experience', 'SCA-UA 9809', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Journalism and Society: Cultural Contexts and African Media', 'SCA-UA 9838', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Queer Cultures and Democracy', 'SCA-UA 9844', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cocoa and Gold: Ghana''s Development in Global Perspective', 'SCA-UA 9852', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Place-Building-Time:The Architecture of Berlin', 'SCA-UA 9853', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cities on the Move', 'SCA-UA 9863', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Immigration', 'SCA-UA 9864', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art and the City: Buenos Aires, New York, Rio de Janeiro and Mexico', 'SCA-UA 9866', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italy During The Renaissance: Florence', 'SCA-UA 9867', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Urban Ethnography', 'SCA-UA 9868', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Gender and Sexuality in France (in French)', 'SCA-UA 9869', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modern Imperialism: 19th & 20th Centuries', 'SCA-UA 9883', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing London', 'SCA-UA 9886', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Current Social, Political and Urban Challenges to European Cities', 'SCA-UA 9890', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ghana (...)', 'SCA-UA GHAN', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Sociology', 'SOC-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sociological Theory', 'SOC-UA 111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Race and Ethnicity', 'SOC-UA 135', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Sociology (Honors)', 'SOC-UA 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research Methods', 'SOC-UA 301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Statistics for Social Research', 'SOC-UA 302', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Law and Society', 'SOC-UA 413', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sociology of Medicine', 'SOC-UA 414', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Immigration', 'SOC-UA 452', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Social Challenges of Climate Change', 'SOC-UA 454', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Modern Societies', 'SOC-UA 9133', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Environmental Social Movements', 'SOC-UA 9209', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar in Sociology Terrorism & Genocide', 'SOC-UA 935', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Seminar: Economy and Society', 'SOC-UA 936', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar: Inequality and Fairness', 'SOC-UA 937', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar: Capstone Research Project', 'SOC-UA 940', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar: Capstone Research Project', 'SOC-UA 941', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Law & Human Rights in Central Europe', 'SOC-UA 9413', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Immigration', 'SOC-UA 9452', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Politics of Organized Crime', 'SOC-UA 9506', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Honors Research Seminar', 'SOC-UA 951', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Current Social, Political and Urban Challenges to European Cities', 'SOC-UA 9690', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Variable Tpcs: (...)', 'SOC-UA 970', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative US and European Human Rights', 'SOC-UA 9709', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Seminar: Shaping an Educ Landscape: Museum Island of BL', 'SOC-UA 9940', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Seminar: Architectural Landscapes of Berlin', 'SOC-UA 9941', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Seminar: The German Intellectual Tradition', 'SOC-UA 9942', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Transnational Migration', 'SOC-UA 9943', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics: (...)', 'SOC-UA 9970', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'SOC-UA 998', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Spanish for Beginners- Level I', 'SPAN-UA 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intens Elemen Spanish', 'SPAN-UA 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Applied Spanish Language Spanish for the Medical Professions', 'SPAN-UA 100', NULL, 'sp2026') ON CONFLICT DO NOTHING;

COMMIT;
