BEGIN;

INSERT INTO classes (name, code, section, semester) VALUES ('Event Operations, Technology and Sustainability', 'TCHT1-UC 3505', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Conferences and Business Events', 'TCHT1-UC 3600', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Casino Operations & Management', 'TCHT1-UC 3620', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Management of Private Clubs & Resorts', 'TCHT1-UC 3640', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'TCHT1-UC 3900', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Consulting Practicum', 'TCHT1-UC 4000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Critical Thinking | Critical Thinking: Big Questions, Many Answers', 'HUMN1-UC 6401', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Foundations of Philosophical Thought', 'HUMN1-UC 6403', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Database Design', 'ISMM1-UC 702', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Project & Innovation Management', 'ISMM1-UC 710', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Disaster Recovery & Continuity Planning', 'ISMM1-UC 725', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Database Administration', 'ISMM1-UC 741', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business Intelligence', 'ISMM1-UC 742', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Computing', 'ISMM1-UC 746', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Networking', 'ISMM1-UC 751', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Systems Analysis', 'ISMM1-UC 752', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Management Info Systems', 'ISMM1-UC 771', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Spec Top in Information Systems Management Extended Reality Technology', 'ISMM1-UC 7990', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Project: Seminar Information Systems Management', 'ISMM1-UC 7991', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interrogating Political Globalization', 'INST1-UC 2010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Resources Management Principles', 'LRMS1-UC 548', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Human Resource Management', 'LRMS1-UC 567', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business Ethics', 'LRMS1-UC 573', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Trade & Investment', 'LRMS1-UC 583', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Supply Chain Management', 'LRMS1-UC 717', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Project: Seminar', 'LRMS1-UC 7991', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Consumer Behavior', 'LRMS1-UC 920', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Market & Managerial Research', 'LRMS1-UC 922', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Advertising, Media, and Public Relations', 'LRMS1-UC 941', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('New Tech for Advertising & Public Relations', 'LRMS1-UC 954', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Global Literature', 'LITR1-UC 6201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Modernism and Literature', 'LITR1-UC 6212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultural and Legal Implications of Digital Technology', 'MKAN1-UC 5100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Marketing', 'MKAN1-UC 5101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Customer Relationship Management', 'MKAN1-UC 5106', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Media Marketing and Analytics', 'MKAN1-UC 5107', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematical Reasoning', 'MATH1-UC 1105', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Math II', 'MATH1-UC 1141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Precalculus', 'MATH1-UC 1171', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Statistical Methods', 'MATH1-UC 1172', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Data and Statistical Narratives for Business Insights', 'MATH1-UC 1176', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Linear Algebra', 'MATH1-UC 1180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Perspectives in Media', 'MEST1-UC 6005', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Children''s Culture and Media', 'MEST1-UC 6010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hip Hop Culture', 'MEST1-UC 6011', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Media', 'MEST1-UC 6012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Understanding Media', 'MEST1-UC 6028', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Documentary Cinema', 'MEST1-UC 6030', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Language of Contemporary Images', 'MEST1-UC 6033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theory of Media & Cultural Studies', 'MEST1-UC 6042', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Organizational Behavior', 'ORBC1-UC 1301', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Multicultural Communication', 'ORBC1-UC 2202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Leadership: Theory & Practice', 'ORBC1-UC 2222', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business Writing', 'ORBC1-UC 2242', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Talent Management and Performance Effectiveness', 'ORBC1-UC 2248', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mindfulness, Spirituality and Meaning in the Workplace', 'ORBC1-UC 2251', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Green Design and the Future of Organizations', 'ORBC1-UC 2253', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Politics', 'POLS1-UC 6601', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Public Opinion and Political Behavior', 'POLS1-UC 6607', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Law', 'POLS1-UC 6661', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('International Human Rights', 'POLS1-UC 6673', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sp Tpcs in Politics Environmental Movements: A Global Perspective', 'POLS1-UC 6690', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Professional Studies Internship', 'PSIN1-UC 7942', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Professional Studies Senior Project Internship', 'PSIN1-UC 7992', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Psychology', 'PSYC1-UC 6801', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Psychology', 'PSYC1-UC 6847', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Clinical Psychology', 'PSYC1-UC 6850', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Forensic Psychology', 'PSYC1-UC 6852', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Perception', 'PSYC1-UC 6873', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Principles', 'REAL1-UC 1001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Law', 'REAL1-UC 1002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Development', 'REAL1-UC 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Accounting & Taxation', 'REAL1-UC 1012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Real Estate Markets in a Global Perspective', 'REAL1-UC 1045', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First Year Experience Course', 'RWLD1-UC 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('First Year Experience II', 'RWLD1-UC 102', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dean''s Global Leadership Development Program', 'RWLD1-UC 200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('SPS Real World (...)', 'RWLD1-UC 4050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Law', 'REBS1-UC 1002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Finance', 'REBS1-UC 1005', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Valuation', 'REBS1-UC 1009', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Development', 'REBS1-UC 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Accounting and Taxation', 'REBS1-UC 1012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Market Analysis in Real Estate', 'REBS1-UC 1015', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Managing the Construction Process: Cost and Project Management Systems', 'REBS1-UC 1033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Data Analytics', 'REBS1-UC 1035', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Capital Markets and Corporate Finance', 'REBS1-UC 1042', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Real Estate Markets', 'REBS1-UC 1045', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Urban Real Estate Economics', 'REBS1-UC 1060', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Environmental, Social and Corporate Governance', 'REBS1-UC 1065', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Management of the Real Estate Firm', 'REBS1-UC 1070', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Financial Modeling for Real Estate', 'REBS1-UC 1100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Statistics for Real Estate Economics', 'REBS1-UC 1101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Private Equity', 'REBS1-UC 1115', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Use of Space and Urban Design in Real Estate', 'REBS1-UC 1120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate and the Community: Legal Basis, Planning and Engagement', 'REBS1-UC 1125', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Special Topics in Real Estate Hotel Development & Investment', 'REBS1-UC 7990', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Senior Project', 'REBS1-UC 7991', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Real Estate Internship', 'REBS1-UC 7992', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Biology', 'SCNC1-UC 2001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Physics of Everyday Life', 'SCNC1-UC 2104', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Darwin to DNA: An Overview of Evolution', 'SCNC1-UC 3218', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Oral Communications', 'SOCS1-UC 2201', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Sciences Research Methods', 'SOCS1-UC 7241', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Project Seminar: Social Sciences', 'SOCS1-UC 7991', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Sociology', 'SOCY1-UC 7200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Deviance and Crime', 'SOCY1-UC 7254', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sociology of Development in Global Perspective', 'SOCY1-UC 7263', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Sports Management', 'TCSM1-UC 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Organizations in Sports', 'TCSM1-UC 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sport Business Practicum', 'TCSM1-UC 1015', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Consumer Behavior', 'TCSM1-UC 1020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Foundations in Sport Entrepreneurship', 'TCSM1-UC 1050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research Methods', 'TCSM1-UC 1055', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Applied Research', 'TCSM1-UC 1060', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Strategies for Academic Succes', 'TCSM1-UC 1071', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Seminar in Sports Management', 'TCSM1-UC 1080', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Financial Management & Accounting in Sport', 'TCSM1-UC 1130', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar in Leadership', 'TCSM1-UC 1350', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship II', 'TCSM1-UC 2010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Studies', 'TCSM1-UC 2020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Public Relations in Sport', 'TCSM1-UC 2100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sports Law', 'TCSM1-UC 2320', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Revenue Generation in Sport', 'TCSM1-UC 2355', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Financial Modeling in Sport', 'TCSM1-UC 2425', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Olympic Sport Governance', 'TCSM1-UC 2440', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Media & Marketing in Sport', 'TCSM1-UC 2520', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intellectual Property & Licensing', 'TCSM1-UC 2540', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('HOW BASKETBALL CAN SAVE THE WORLD An Exploration of Society, Politics, Culture/Commerce Through/game', 'TCSM1-UC 2550', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ethical Issues in Sport', 'TCSM1-UC 2640', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sociology of Sport', 'TCSM1-UC 2650', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Marketing Research & Analytics', 'TCSM1-UC 3020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sport Broadcasting', 'TCSM1-UC 3100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('From Field to Screen: Making the Sport Film', 'TCSM1-UC 3120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Entrepreneurship I: Incubator Phase', 'TCSM1-UC 3300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Entrepreneurship II: Accelerator Phase', 'TCSM1-UC 3310', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Live Sport Event Management', 'TCSM1-UC 3420', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sport Marketing', 'TCSM1-UC 3660', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sport Sponsorship Strategies', 'TCSM1-UC 3700', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'TCSM1-UC 3850', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sport Industry Thesis', 'TCSM1-UC 3920', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Emerging Issues in Sports Business', 'TCSM1-UC 3950', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Athlete Studies', 'TCSM1-UC 4000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Writing and Research', 'ACE-UE 110', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'ASL-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Sign Language I', 'ASL-UE 91', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Sign Language II', 'ASL-UE 92', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Sign Language III', 'ASL-UE 93', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('American Sign Language IV', 'ASL-UE 94', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Developmental Psychology', 'APSY-UE 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'APSY-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Counseling Interview', 'APSY-UE 1012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mental Health: Historical, Social and Politcal Perspectives', 'APSY-UE 1031', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Professional Development in Applied Psychology', 'APSY-UE 1034', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Abnormal Psychology', 'APSY-UE 1038', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Cultures of Psychology', 'APSY-UE 1050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sexual Identities Across The Lifespan', 'APSY-UE 1110', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar in Applied Psychology I: Principles & Practices', 'APSY-UE 1124', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Seminar in Applied Psychology II: Theory, Research & Practice', 'APSY-UE 1125', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research Methods in Applied Psychology II', 'APSY-UE 1137', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Children''s Learning: Theory & Research', 'APSY-UE 1214', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Child Development in a Socio-Culture Context', 'APSY-UE 1215', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Intervention in Schools and Communities', 'APSY-UE 1270', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Developmental Psychology Across the Lifespan', 'APSY-UE 1271', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Adolescent Development', 'APSY-UE 1272', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Child Development and Social Policy in a Global Society', 'APSY-UE 1279', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Parenting and Culture', 'APSY-UE 1280', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Psychology', 'APSY-UE 13', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Group Dynamics', 'APSY-UE 1620', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Honors Seminar in Applied Psychology II', 'APSY-UE 1996', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Psychology and Its Principles', 'APSY-UE 2', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Development I', 'APSY-UE 20', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Development II: Application for Early Childhood Educators', 'APSY-UE 21', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Development II: Application for Childhood Educators', 'APSY-UE 22', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Development II: Early Adolescents and Adolescents', 'APSY-UE 23', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research Methods in Applied Psychology I', 'APSY-UE 25', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Community Psychology', 'APSY-UE 5', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Community Psychology', 'APSY-UE 9005', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Development I', 'APSY-UE 9020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Development II: Application for Early Childhood Educators', 'APSY-UE 9021', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Development II: Application for Childhood Educators', 'APSY-UE 9022', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Human Development II: Early Adolescents and Adolescents', 'APSY-UE 9023', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Basic Statistics I', 'APSTA-UE 1085', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cracking the Code', 'APSTA-UE 21', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Carpe Datum: Data Science for Life’s Big Questions', 'APSTA-UE 25', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('History of Fashion Photography', 'ARCS-UE 1020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fashion in Context', 'ARCS-UE 1088', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('How to: (analyze) Fashion', 'ARCS-UE 1098', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Paris to New York: Nineteenth Century Fashion', 'ARCS-UE 1099', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art: Practice & Ideas', 'ARTCR-UE 10', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art and Contemporary Culture I', 'ARTCR-UE 37', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Art: Professional Practices', 'ARTCR-UE 52', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art of Now', 'ARTCR-UE 55', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Art & Ideas: Art World Today - Berlin & Beyond', 'ARTCR-UE 9153', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Topics in Visual & Culture: Art in Contemporary Culture', 'ARTCR-UE 9161', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Science and Health in Childhood Education', 'CHDED-UE 1141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Studies from Multicultural Perspectives in Childhood Education', 'CHDED-UE 1142', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Integrating Children’s Literature and Technology in Childhood Education', 'CHDED-UE 1144', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Integrated Arts in Early Childhood and Childhood Education.', 'CHDED-UE 1145', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Childhood Education II', 'CHDED-UE 1901', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Childhood Education III', 'CHDED-UE 1902', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ind Study', 'CSCD-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Talking Brain: Typical and Disordered Communication', 'CSCD-UE 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Science of Language', 'CSCD-UE 110', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Acoustic Phonetics', 'CSCD-UE 1202', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Audiology: Intervention Strategies Across the Lifespan', 'CSCD-UE 1222', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Speech & Language Development in Children', 'CSCD-UE 1601', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Anatomy/Physiology of Speech/Hearing Mechanism', 'CSCD-UE 231', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Yoga and Pilates: Dynamic Alignment Princples', 'MPADE-UE 1006', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tap Dance', 'MPADE-UE 1013', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Hip Hop Dance Culture', 'MPADE-UE 1015', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Jazz Dance Technique', 'MPADE-UE 1029', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Modern Dance', 'MPADE-UE 12', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dance as an Art Form', 'MPADE-UE 1278', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Beginning Ballet', 'MPADE-UE 14', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intercultural Dance', 'MPADE-UE 1541', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('West African Dance', 'MPADE-UE 1701', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Afro-Caribbean Dance', 'MPADE-UE 1702', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('NYU Orchestra', 'MPAGC-UE 1087', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Creating a Career as a Musician', 'MPAGC-UE 1229', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Multilingual Learners in Early Childhood', 'ECED-UE 1033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'EDST-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Political Economy of Education: Why Does College Cost So Much?', 'EDST-UE 1321', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Education and Social Entrepreneurship', 'EDST-UE 1503', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Education Studies Internship', 'EDST-UE 1605', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Senior Seminar', 'EDST-UE 1990', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ind Study', 'MPAET-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Design for The Stage', 'MPAET-UE 1017', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Acting: Fundamentals', 'MPAET-UE 1050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Acting: Scene Study', 'MPAET-UE 1051', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Acting:Character Study', 'MPAET-UE 1052', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Voice/Speech for Actors', 'MPAET-UE 1055', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Drama Activities in the Secondary Classroom', 'MPAET-UE 1068', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Verbatim Performance Lab Internship', 'MPAET-UE 1117', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Applied Theatre Praxis', 'MPAET-UE 1978', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Educ Theatre I', 'MPAET-UE 50', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Theatre as Art Form', 'MPAET-UE 60', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Critical Linguistics :Language, Power, and Society', 'ENGED-UE 1589', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching English Education:Middle School', 'ENGED-UE 1911', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching English Education:High School', 'ENGED-UE 1922', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Reading of Poetry', 'ENGED-UE 193', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('What on Earth Should We Eat?', 'FOOD-UE 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Beverages', 'FOOD-UE 1025', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Intro to Urban Agriculture', 'FOOD-UE 1030', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food Systems: Food and Agriculture', 'FOOD-UE 1033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food and the City', 'FOOD-UE 1050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Food Stud & Food Mgmt', 'FOOD-UE 1056', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Research in Food Studies', 'FOOD-UE 1118', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Essentials of Cuisine:', 'FOOD-UE 1135', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food and Nutrition Global Society', 'FOOD-UE 1180', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Techin/Regional Cuisine', 'FOOD-UE 1183', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Sustainability and Health', 'FOOD-UE 1184', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food in The Arts:', 'FOOD-UE 1204', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Food History', 'FOOD-UE 1210', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food Photography', 'FOOD-UE 1271', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Culture & Globalization: Buenos Aires', 'FOOD-UE 9182', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Culture & Globalization: London', 'FOOD-UE 9184', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Culture & Globalization: Florence', 'FOOD-UE 9185', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Culture & Globalization: Accra', 'FOOD-UE 9186', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Culture & Globalization: Tel Aviv', 'FOOD-UE 9187', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Culture & Globalization: Prague', 'FOOD-UE 9190', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Culture & Globalization: Sydney', 'FOOD-UE 9191', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Food, Culture & Globalization: Berlin', 'FOOD-UE 9192', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to US Education', 'HSED-UE 1005', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Culture Wars', 'HSED-UE 1033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Berkeley’s Free Speech Movement & the Student Rights Revolution of the 1960s', 'HSED-UE 1037', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comparative Politics, Education and Conflict', 'INTE-UE 1028', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Globalization and Education', 'INTE-UE 11', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Interdisciplinary Perspectives on the New Immigration', 'INTE-UE 1545', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Foundations of Literacy Development', 'LITC-UE 1176', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Mathematics in Early Childhood Education II', 'MTHED-UE 1033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Educational Technology in Secondary School Mathematics', 'MTHED-UE 1044', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Geometry for Teachers', 'MTHED-UE 1046', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Counting and Chance', 'MTHED-UE 1051', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Teaching of Computer Science', 'MTHED-UE 1080', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Mathematics Education: Middle and High School I', 'MTHED-UE 1911', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Mathematics Education: Middle and High School II', 'MTHED-UE 1922', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Media Studies', 'MCC-UE 1', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Space and Place in Human Communication', 'MCC-UE 1002', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Television:History/Form', 'MCC-UE 1006', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Film:History and Form', 'MCC-UE 1007', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Psychoanalysis: Desire and Culture', 'MCC-UE 1009', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media and Migration', 'MCC-UE 1011', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Crime, Violence & Media', 'MCC-UE 1012', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Political Communication', 'MCC-UE 1013', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advertising and Consumer Society', 'MCC-UE 1015', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media Audiences', 'MCC-UE 1016', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media & Identity', 'MCC-UE 1019', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business of Media', 'MCC-UE 1020', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Dead Media Research Studio', 'MCC-UE 1021', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Latino Media', 'MCC-UE 1022', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Disability, Technology and media', 'MCC-UE 1026', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media and the Environment', 'MCC-UE 1027', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Architecture as Media:', 'MCC-UE 1030', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Media: Context and Practice', 'MCC-UE 1031', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Social Media Practicum', 'MCC-UE 1032', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Critical Making', 'MCC-UE 1033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Technology and Society', 'MCC-UE 1034', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media and Music', 'MCC-UE 1037', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Queer and Trans Game Studies', 'MCC-UE 1043', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Black Screen Cultures', 'MCC-UE 1044', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media Events and Spectacles', 'MCC-UE 1065', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship', 'MCC-UE 1100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Psychic Life of Media', 'MCC-UE 1105', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Projecting History', 'MCC-UE 1140', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Critical Video: Theory & Practice', 'MCC-UE 1142', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cultural Capital: Media and Arts in New York City', 'MCC-UE 1152', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Coding Workshop', 'MCC-UE 1154', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Inquiry Seminar', 'MCC-UE 1200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media and Globalization', 'MCC-UE 1300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Media and International Law', 'MCC-UE 1304', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Culture & Media in Urban China', 'MCC-UE 1310', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Middle East Media', 'MCC-UE 1341', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fashion and Power', 'MCC-UE 1345', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fame', 'MCC-UE 1346', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Data and Society', 'MCC-UE 1349', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('War as Media', 'MCC-UE 1351', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Revolution and Media', 'MCC-UE 1352', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Methods in Media Studies', 'MCC-UE 14', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Cult/Identities', 'MCC-UE 1401', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Postcolonial Visual Culture', 'MCC-UE 1403', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Media and Culture of Money', 'MCC-UE 1404', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Copyright, Commerce and Culture', 'MCC-UE 1405', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Gender, Sex and The Global', 'MCC-UE 1407', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Queer and Trans Identity', 'MCC-UE 1408', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Consumption, Culture and Identity', 'MCC-UE 1409', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Visual Culture', 'MCC-UE 1412', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Business Structure of The Music Industry', 'MPAMB-UE 100', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Data Analysis in the Music Industry: Introduction & Applications', 'MPAMB-UE 101', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Strategic Music and Branding', 'MPAMB-UE 105', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Artists and Repertoire: Talent Discovery and Development', 'MPAMB-UE 1050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Stress-free Living & Working in the Music Industry', 'MPAMB-UE 1307', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Village Records:Pract Recorded Music Industry', 'MPAMB-UE 1310', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Writing in the Music Industry', 'MPAMB-UE 1312', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('The Business of Podcasting', 'MPAMB-UE 1313', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Technological Transformation of the Music Industry', 'MPAMB-UE 1315', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Music Business', 'MPAMB-UE 1320', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Entrepreneurship for The Music Industry', 'MPAMB-UE 1400', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Concert Management', 'MPAMB-UE 200', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Publishing', 'MPAMB-UE 205', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music in Media Business', 'MPAMB-UE 210', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Int''L Music Business Marketplace', 'MPAMB-UE 300', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Publishing', 'MPAMB-UE 9205', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MPAME-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Recital', 'MPAME-UE 1092', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Elementary Schools', 'MPAME-UE 1141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Student Teaching in Secondary Schools', 'MPAME-UE 1145', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MPABR-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brass Instruments (Private Lessons)', 'MPABR-UE 1111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brass Choir', 'MPABR-UE 1121', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brass Pedagogy', 'MPABR-UE 1124', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('NYU Chamber Ensembles', 'MPABR-UE 1131', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brass and Piano Repertoire', 'MPABR-UE 1141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Recital', 'MPABR-UE 1181', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brass Instruments (Pvt Lessons)Non-Majors', 'MPABR-UE 1211', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brass Instruments (Prvt Lesson) for Non-Majors II', 'MPABR-UE 1212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brass Instruments (Private Lessons)', 'MPABR-UE 9111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Jazz Theory & Ear Training I', 'MPAJZ-UE 1039', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Jazz Theory & Ear Training II', 'MPAJZ-UE 1040', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Instrumental Jazz (Private Lessons)', 'MPAJZ-UE 1070', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Jazz Ensemble', 'MPAJZ-UE 1089', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Recital', 'MPAJZ-UE 1092', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Jazz Arranging & Composition II', 'MPAJZ-UE 1120', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Jazz History', 'MPAJZ-UE 1121', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Chicago Blues', 'MPAJZ-UE 1602', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Afro-Cuban Music', 'MPAJZ-UE 1604', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Miles Davis Aesthetic', 'MPAJZ-UE 1608', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Brazilian Music', 'MPAJZ-UE 1610', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Guitar (Group) for Non-Majors', 'MPAJZ-UE 41', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Pop/Jazz Guitar (Private Lessons) for Non-Majors', 'MPAJZ-UE 70', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Pop/Jazz Piano (Prvt Lessons) for Non-Majors', 'MPAJZ-UE 71', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Pop/Jazz Bass (Prvt Lessons) for Non-Majors', 'MPAJZ-UE 72', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Pop/Jazz Saxophone (Prvt Lessons) for Non-Majors', 'MPAJZ-UE 73', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Pop/Jazz Trumpet (Prvt Lessons) for Non Majors', 'MPAJZ-UE 74', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('NYU Jazz Ensembles', 'MPAJZ-UE 9089', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Percussion Instruments (Private Lessons)', 'MPAPS-UE 1111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Percussion Ensembles', 'MPAPS-UE 1131', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Percussion Performance Juries', 'MPAPS-UE 1136', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Percussion Laboratory', 'MPAPS-UE 1151', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Recital', 'MPAPS-UE 1181', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Percussion Instruments (Pvt Lessons)Non-Majors', 'MPAPS-UE 1211', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Percussion Instruments (Prvt lessons) for Non-Majors II', 'MPAPS-UE 1212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Music Ensemble', 'MPAPS-UE 1221', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Percussion Instruments (Private Lessons)', 'MPAPS-UE 9111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Piano (Private Lessons) for Music Majors', 'MPAPE-UE 1056', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Collaborative Piano: Techniques & Practicum', 'MPAPE-UE 1070', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('NYU Chamber Ensembles', 'MPAPE-UE 1080', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Recital', 'MPAPE-UE 1092', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Piano (Private Lessons) for Non-Majors', 'MPAPE-UE 56', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Keyboard Skills I', 'MPAPE-UE 72', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Keyboard Skills II', 'MPAPE-UE 73', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Keyboard Skills IV', 'MPAPE-UE 75', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Piano(Private Lessons)', 'MPAPE-UE 9045', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Keyboard Skills II', 'MPAPE-UE 9073', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Keyboard Skills IV', 'MPAPE-UE 9075', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MPASS-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Stringed Instruments (Private Lessons)', 'MPASS-UE 1111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Alexander Technique (Private Lessons)', 'MPASS-UE 1112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Chamber Ensembles', 'MPASS-UE 1131', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Baroque Ensemble', 'MPASS-UE 1132', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Audition Class', 'MPASS-UE 1134', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Improvisation Class', 'MPASS-UE 1135', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('String Performance Juries', 'MPASS-UE 1136', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Violin Class', 'MPASS-UE 1141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Viola Class', 'MPASS-UE 1142', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cello Class', 'MPASS-UE 1143', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Bass Class', 'MPASS-UE 1144', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Violin Orchestral Repertoire', 'MPASS-UE 1151', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Cello Orchestral Repertoire', 'MPASS-UE 1153', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Harp Orchestral Repertoire', 'MPASS-UE 1155', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Violin Pedagogy', 'MPASS-UE 1161', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Violin Technique Class', 'MPASS-UE 1171', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Bass Technique Class', 'MPASS-UE 1174', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Harp Technique Class', 'MPASS-UE 1175', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Recital', 'MPASS-UE 1181', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Stringed Instruments (Pvt Lessons) Non-Majors', 'MPASS-UE 1211', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Stringed Instruments (Prvt Lesson) for Non-Majors', 'MPASS-UE 1212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Stringed Instruments (Private Lessons)', 'MPASS-UE 9111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MPAVP-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vocal Training (Private Lessons)', 'MPAVP-UE 1111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vocal Coaching', 'MPAVP-UE 1112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Alexander Technique (Private Lessons)', 'MPAVP-UE 1113', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Recital', 'MPAVP-UE 1122', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Beginning Ballet', 'MPAVP-UE 1123', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Jazz Dance Technique', 'MPAVP-UE 1125', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Tap Dance', 'MPAVP-UE 1126', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Theatre Dance', 'MPAVP-UE 1127', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Italian Diction for Singers', 'MPAVP-UE 1131', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('French Diction for Singers', 'MPAVP-UE 1134', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Acting II for Singers', 'MPAVP-UE 1142', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Song Analysis', 'MPAVP-UE 1168', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('NYU Chamber Ensembles', 'MPAVP-UE 1181', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Voice Workshop: Techniques I', 'MPAVP-UE 1251', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Voice Workshop: Live Performance Lab', 'MPAVP-UE 1253', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Voice Workshop: Recording Capstone', 'MPAVP-UE 1255', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Voice Workshop: Phonetics for the Vocalist', 'MPAVP-UE 1259', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Song Repertoire: Italian Spanish', 'MPAVP-UE 1263', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Song Repertoire: French', 'MPAVP-UE 1264', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Theatre Workshop: Song Analysis II', 'MPAVP-UE 1322', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Theatre Workshop: Scene Study', 'MPAVP-UE 1323', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Theatre Hist II', 'MPAVP-UE 1352', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vocal Training Non-Musv Majors', 'MPAVP-UE 1410', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vocal Training (Private Lesson) for Non-Majors', 'MPAVP-UE 1512', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vocal Training (Private Lesson) for Non-Majors', 'MPAVP-UE 1514', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Vocal Training (Private Lessons)', 'MPAVP-UE 9111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MPAWW-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('NYU Wind Symphony:', 'MPAWW-UE 1083', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Wind Instrument (Private Lessons)', 'MPAWW-UE 1111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Saxophone Orchestra', 'MPAWW-UE 1123', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('NYU Chamber Ensembles', 'MPAWW-UE 1131', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Orchestral Flutes', 'MPAWW-UE 1132', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Flute Studio Class', 'MPAWW-UE 1141', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Clarinet Studio Class', 'MPAWW-UE 1142', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Double Reed Studio Class', 'MPAWW-UE 1143', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Saxophone Studio Class', 'MPAWW-UE 1144', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Recital', 'MPAWW-UE 1181', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Wind Instruments (Pvt Lessons)Non-Majors', 'MPAWW-UE 1211', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Wind Instruments (Prvt Lessons) for Non-Majors II', 'MPAWW-UE 1212', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Wind Instrument (Private Lessons)', 'MPAWW-UE 9111', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Independent Study', 'MPATE-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Analog Recording Technology', 'MPATE-UE 1001', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Recording Technology', 'MPATE-UE 1003', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Applied Studio Production', 'MPATE-UE 1006', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fund of Audio Tech II: Stu Maint', 'MPATE-UE 1009', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Audio for Video', 'MPATE-UE 1010', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Concert Recording', 'MPATE-UE 1011', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Midi Technology II', 'MPATE-UE 1014', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Electronic Music Performance', 'MPATE-UE 1019', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Rcdg Tech for Non Majors', 'MPATE-UE 1022', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Elect Music Synthesis: Fundamental Techn', 'MPATE-UE 1037', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Global Electronic Music I', 'MPATE-UE 1038', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Comp Music Synthesis: Fundamental Techniques', 'MPATE-UE 1047', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Software Music Production', 'MPATE-UE 1070', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Live Sound Reinforcement', 'MPATE-UE 1112', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music, the Mind and Artificial Intelligence', 'MPATE-UE 1113', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Applied Audio for Video', 'MPATE-UE 1225', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Aesthetics of Recording', 'MPATE-UE 1227', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Advanced Topics in Music Technology: Multichannel Media Installation and Performance', 'MPATE-UE 1633', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Fundamentals of Music Technology', 'MPATE-UE 1801', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Midi for Non-Majors', 'MPATE-UE 1810', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Analog Electronics', 'MPATE-UE 1817', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Electronics', 'MPATE-UE 1818', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Internship in Music Technology', 'MPATE-UE 1820', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Analog Electronics Lab', 'MPATE-UE 1827', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Digital Electronics Lab', 'MPATE-UE 1828', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Technology Undergraduate Capstone Project', 'MPATE-UE 1900', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Electroacoustic Comp', 'MPATE-UE 9047', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Listening to Paris: Sound, Space and Creation at IRCAM | Sound Design and Spatialization at IRCAM', 'MPATE-UE 9055', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Ind Study', 'MPATC-UE 1000', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Screen Scoring Recording Sessions', 'MPATC-UE 1016', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('16th-Century Counterpoint', 'MPATC-UE 1018', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Composition (Private Lessons)', 'MPATC-UE 1021', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music Theory for Non-Majors', 'MPATC-UE 1022', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Group Composition (Non-Majors): Beginner Screen Scoring', 'MPATC-UE 1032', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Group Composition (Non-Majors): Beginner Concert Music', 'MPATC-UE 1033', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Music History: Gender and Sexuality in Music', 'MPATC-UE 1048', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Contemporary Scoring: Creative & Technological Practices', 'MPATC-UE 1049', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('MIDI and DAW Production Studio', 'MPATC-UE 1050', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Production', 'MPATC-UE 1051', NULL, 'sp2026') ON CONFLICT DO NOTHING;
INSERT INTO classes (name, code, section, semester) VALUES ('Introduction to Songwriting', 'MPATC-UE 1052', NULL, 'sp2026') ON CONFLICT DO NOTHING;

COMMIT;
